export const games = [
  { name: '1-2-Switch', image: './covers/1-2-Switch.jpg' },
  { name: '13 Sentinels: Aegis Rim', image: './covers/13 Sentinels Aegis Rim.jpg' },
  { name: '30-in-1 Game Collection', image: './covers/30-in-1-Game-Collection.jpg' },
  { name: 'Ace Angler Fishing Spirits M', image: './covers/Ace Angler Fishing Spirits M.jpg' },
  { name: 'Ace Attorney Investigations Collection', image: './covers/Ace-Attorney-Investigations-Collection.jpg' },
  { name: 'Ace Combat 7: Skies Unknown Deluxe Edition', image: './covers/Ace Combat 7- Skies Unknown Deluxe Edition.jpg' },
  { name: 'Advance Wars 1+2: Re-Boot Camp', image: './covers/Advance-Wars-1+2--Re-Boot-Camp.jpg' },
  { name: 'Afterimage', image: './covers/Afterimage.jpg' },
  { name: 'AI: The Somnium Files', image: './covers/AI--The-Somnium-Files.jpg' },
  { name: 'AI: The Somnium Files - nirvanA Initiative', image: './covers/AI--The-Somnium-Files-a-nirvanA-Initiative.jpg' },
  { name: 'Alex Kidd in Miracle World DX', image: './covers/Alex-Kidd-in-Miracle-World-DX.jpg' },
  { name: 'Alice Gear Aegis CS: Concerto of Simulatrix', image: './covers/Alice-Gear-Aegis-CS--Concerto-of-Simulatrix.jpg' },
  { name: 'All-Star Fruit Racing', image: './covers/All-Star Fruit Racing.jpg' },
  { name: 'Animal Crossing: New Horizons', image: './covers/Animal-Crossing--New-Horizons.jpg' },
  { name: 'Another Code: Recollection', image: './covers/Another Code- Recollection.jpg' },
  { name: 'Apollo Justice: Ace Attorney Trilogy', image: './covers/Apollo Justice- Ace Attorney Trilogy.jpg' },
  { name: 'ARK: Survival Evolved', image: './covers/ARK- Survival Evolved.jpg' },
  { name: 'Arms', image: './covers/Arms.jpg' },
  { name: 'Assassin\'s Creed III: Remastered', image: './covers/Assassins Creed III- Remastered.jpg' },
  { name: 'Assassin\'s Creed: The Ezio Collection', image: './covers/Assassins Creed- The Ezio Collection.jpg' },
  { name: 'Assassin\'s Creed: The Rebel Collection', image: './covers/Assassins Creed- The Rebel Collection.jpg' },
  { name: 'Astral Chain', image: './covers/Astral-Chain.jpg' },
  { name: 'Astroneer', image: './covers/Astroneer.jpg' },
  { name: 'Attack on Titan 2: Final Battle', image: './covers/Attack on Titan 2- Final Battle.jpg' },
  { name: 'Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings', image: './covers/Atelier Lydie & Suelle- The Alchemists and the Mysterious Paintings.jpg' },
  { name: 'Atelier Ryza: Ever Darkness & the Secret Hideout', image: './covers/Atelier Ryza- Ever Darkness & the Secret Hideout.jpg' },
  { name: 'Atelier Ryza 2: Lost Legends & the Secret Fairy', image: './covers/Atelier Ryza 2- Lost Legends & the Secret Fairy.jpg' },
  { name: 'Atelier Ryza 3: Alchemist of the End & the Secret Key', image: './covers/Atelier Ryza 3- Alchemist of the End & the Secret Key.jpg' },
  { name: 'Atelier Sophie: The Alchemist of the Mysterious Book DX', image: './covers/Atelier-Sophie--The-Alchemist-of-the-Mysterious-Book-DX.jpg' },
  { name: 'Atelier Sophie 2: The Alchemist of the Mysterious Dream', image: './covers/Atelier-Sophie-2--The-Alchemist-of-the-Mysterious-Dream.jpg' },
  { name: 'Avatar: The Last Airbender - Quest for Balance', image: './covers/Avatar- The Last Airbender- Quest for Balance.jpg' },
  { name: 'Azur Lane: Crosswave', image: './covers/Azur Lane- Crosswave.jpg' },
  { name: 'Azure Striker Gunvolt: Striker Pack', image: './covers/Azure Striker Gunvolt- Striker Pack.jpg' },
  { name: 'Azure Striker Gunvolt 3', image: './covers/Azure Striker Gunvolt 3.jpg' },
  { name: 'Bakugan: Champions of Vestroia', image: './covers/Bakugan- Champions of Vestroia.jpg' },
  { name: 'Balan Wonderworld', image: './covers/Balan Wonderworld.jpg' },
  { name: 'Balatro', image: './covers/Balatro.jpg' },
  { name: 'Battle Chasers: Nightwar', image: './covers/Battle Chasers- Nightwar.jpg' },
  { name: 'Bayonetta', image: './covers/Bayonetta.jpg' },
  { name: 'Bayonetta 2', image: './covers/Bayonetta 2.jpg' },
  { name: 'Bayonetta 3', image: './covers/Bayonetta 3.jpg' },
  { name: 'Bayonetta Origins: Cereza and the Lost Demon', image: './covers/Bayonetta Origins- Cereza and the Lost Demon.jpg' },
  { name: 'Bear & Breakfast', image: './covers/Bear & Breakfast.jpg' },
  { name: 'Beasties', image: './covers/Beasties.jpg' },
  { name: 'Big Brain Academy', image: './covers/Big Brain Academy.jpg' },
  { name: 'BioShock Remastered', image: './covers/BioShock Remastered.jpg' },
  { name: 'Birushana: Rising Flower of Genpei', image: './covers/Birushana- Rising Flower of Genpei.jpg' },
  { name: 'Blasphemous', image: './covers/Blasphemous 2.jpg' },
  { name: 'Blasphemous 2', image: './covers/Blasphemous 2.jpg' },
  { name: 'Bloodstained: Ritual of the Night', image: './covers/Bloodstained- Ritual of the Night.jpg' },
  { name: 'Bluey: The Videogame', image: './covers/Bluey- The Videogame.jpg' },
  { name: 'Borderlands: Game of the Year Edition', image: './covers/Borderlands- Game of the Year Edition.jpg' },
  { name: 'Borderlands 3 Ultimate Edition', image: './covers/Borderlands 3 Ultimate Edition.jpg' },
  { name: 'Bravely Default II', image: './covers/Bravely Default II.jpg' },
  { name: 'Brigandine: The Legend of Runersia', image: './covers/Brigandine- The Legend of Runersia.jpg' },
  { name: 'Brilliant and Brilliant, My Family Modern Era (Hanayaka Nari, Waga Ichizoku Modern Nostalgie)', image: './covers/Brilliant and Brilliant, My Family Modern Era (Hanayaka Nari, Waga Ichizoku Modern Nostalgie).png' },
  { name: 'Bubble Bobble 4 Friends: The Baron is Back!', image: './covers/Bubble Bobble 4 Friends- The Baron is Back!.jpg' },
  { name: 'Buddy Mission: Bond', image: './covers/Buddy Mission- Bond.jpg' },
  { name: 'Bunny Garden', image: './covers/Bunny Garden.jpg' },
  { name: 'Burnout Paradise Remastered', image: './covers/Burnout Paradise Remastered.jpg' },
  { name: 'Capcom Belt Action Collection', image: './covers/Capcom Belt Action Collection.jpg' },
  { name: 'Capcom Fighting Collection', image: './covers/Capcom Fighting Collection.jpg' },
  { name: 'Captain Toad: Treasure Tracker', image: './covers/Captain Toad- Treasure Tracker.jpg' },
  { name: 'Captain Tsubasa: Rise of New Champions', image: './covers/Captain Tsubasa- Rise of New Champions.jpg' },
  { name: 'Carnival Games', image: './covers/Carnival Games.jpg' },
  { name: 'Castle Crashers Remastered v1.0.5', image: './covers/Castle Crashers Remastered.jpg' },
  { name: 'Cat Quest v1.01', image: './covers/Cat Quest.jpg' },
  { name: 'Cat Quest II v1.0.4', image: './covers/Cat Quest II.jpg' },
  { name: 'Catherine: Full Body', image: './covers/Catherine- Full Body.jpg' },
  { name: 'Celeste v1.4.1.1', image: './covers/Celeste.jpg' },
  { name: 'Chef Life: A Restaurant Simulator', image: './covers/Chef Life- A Restaurant Simulator.jpg' },
  { name: 'Chocobo GP Lite + DLC v1.0.1', image: './covers/Chocobo GP Lite.png' },
  { name: 'Cities: Skylines v1.0.3.37670', image: './covers/Cities- Skylines.jpg' },
  { name: 'Cloudpunk', image: './covers/Cloudpunk.jpg' },
  { name: 'Clubhouse Games: 51 Worldwide Classics v1.1.2', image: './covers/Clubhouse Games- 51 Worldwide Classics.jpg' },
  { name: 'Collection of Mana', image: './covers/Collection of Mana.jpg' },
  { name: 'Contra Anniversary Collection v1.1.0', image: './covers/Contra Anniversary Collection.jpg' },
  { name: 'Contra: Operation Galuga v1.0.876634', image: './covers/Contra- Operation Galuga.jpg' },
  { name: 'Crash Bandicoot 4: It\'s About Time', image: './covers/Crash Bandicoot 4- Its About Time.jpg' },
  { name: 'Crash Bandicoot N. Sane Trilogy', image: './covers/Crash Bandicoot N. Sane Trilogy.jpg' },
  { name: 'Crash Team Racing Nitro-Fueled', image: './covers/Crash Team Racing Nitro-Fueled.jpg' },
  { name: 'Cris Tales', image: './covers/Cris Tales.jpg' },
  { name: 'Crisis Core: Final Fantasy VII Reunion', image: './covers/Crisis Core- Final Fantasy VII Reunion.jpg' },
  { name: 'Cruis\'n Blast v1.06', image: './covers/Cruis\'n Blast.jpg' },
  { name: 'Crypt of the NecroDancer', image: './covers/Crypt of the NecroDancer.jpg' },
  { name: 'Crysis Remastered', image: './covers/Crysis Remastered.jpg' },
  { name: 'Crystar', image: './covers/Crystar.jpg' },
  { name: 'Cult of the Lamb v1.2.6', image: './covers/Cult of the Lamb.jpg' },
  { name: 'Cuphead + DLC v1.3.4', image: './covers/Cuphead.jpg' },
  { name: 'Cupid Parasite', image: './covers/Cupid Parasite.jpg' },
  { name: 'Curse of the Sea Rats', image: './covers/Curse of the Sea Rats.jpg' },
  { name: 'Dance with Devils', image: './covers/Dance with Devils.jpg' },
  { name: 'Danganronpa: Trigger Happy Havoc Anniversary Edition', image: './covers/Danganronpa- Trigger Happy Havoc Anniversary Edition.jpg' },
  { name: 'Danganronpa 2: Goodbye Despair Anniversary Edition', image: './covers/Danganronpa 2- Goodbye Despair Anniversary Edition.jpg' },
  { name: 'Danganronpa V3: Killing Harmony Anniversary Edition', image: './covers/Danganronpa V3- Killing Harmony Anniversary Edition.jpg' },
  { name: 'Danganronpa S: Ultimate Summer Camp', image: './covers/Danganronpa S- Ultimate Summer Camp.jpg' },
  { name: 'Dark Souls: Remastered', image: './covers/Dark Souls- Remastered.jpg' },
  { name: 'Darksiders II Deathinitive Edition', image: './covers/Darksiders II Deathinitive Edition.jpg' },
  { name: 'Darksiders III', image: './covers/Darksiders III.jpg' },
  { name: 'Darksiders Warmastered Edition', image: './covers/Darksiders Warmastered Edition.jpg' },
  { name: 'Dave the Diver + DLC v1.0.2.651', image: './covers/Dave the Diver.jpg' },
  { name: 'Days of Doom', image: './covers/Days of Doom.jpg' },
  { name: 'DC Super Hero Girls: Teen Power', image: './covers/DC Super Hero Girls- Teen Power.jpg' },
  { name: 'DC\'s Justice League: Cosmic Chaos', image: './covers/DCs Justice League- Cosmic Chaos.jpg' },
  { name: 'Dead Cells + 5 DLC v1.23.1', image: './covers/Dead Cells.jpg' },
  { name: 'Dead or Alive Xtreme 3 Scarlet + 11 DLC', image: './covers/Dead or Alive Xtreme 3 Scarlet.jpg' },
  { name: 'Deadly Premonition 2: A Blessing In Disguise', image: './covers/Deadly Premonition 2- A Blessing In Disguise.jpg' },
  { name: 'Daemon X Machina', image: './covers/Daemon X Machina.jpg' },
  { name: 'Demon Slayer -Kimetsu no Yaiba- Sweep the Board!', image: './covers/Demon Slayer -Kimetsu no Yaiba- Sweep the Board!.jpg' },
  { name: 'Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles', image: './covers/Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles.jpg' },
  { name: 'Detective Pikachu Returns', image: './covers/Detective Pikachu Returns.jpg' },
  { name: 'Devil May Cry', image: './covers/Devil May Cry.jpg' },
  { name: 'Diablo III: Eternal Collection', image: './covers/Diablo III- Eternal Collection.jpg' },
  { name: 'Digimon Story: Cyber Sleuth Hacker\'s Memory', image: './covers/Digimon Story- Cyber Sleuth Hackers Memory.jpg' },
  { name: 'Digimon Survive', image: './covers/Digimon Survive.jpg' },
  { name: 'Disco Elysium - The Final Cut v1.03', image: './covers/Disco Elysium - The Final Cut.jpg' },
  { name: 'Disgaea 4 Complete+', image: './covers/Disgaea 4 Complete+.jpg' },
  { name: 'Disgaea 5: Alliance of Vengeance', image: './covers/Disgaea 5- Alliance of Vengeance.jpg' },
  { name: 'Disgaea 6: Defiance of Destiny', image: './covers/Disgaea 6- Defiance of Destiny.jpg' },
  { name: 'Disney Classic Games: Aladdin and The Lion King + DLC v1.5.0', image: './covers/Disney Classic Games- Aladdin and The Lion King.jpg' },
  { name: 'Disney Illusion Island v1.0.1', image: './covers/Disney Illusion Island.jpg' },
  { name: 'Divinity: Original Sin 2 - Definitive Edition v1.0.3.1', image: './covers/Divinity- Original Sin 2 – Definitive Edition.jpg' },
  { name: 'Doki Doki Literature Club Plus! v1.0.3', image: './covers/Doki Doki Literature Club Plus!.jpg' },
  { name: 'Donkey Kong Country: Tropical Freeze v1.0.1', image: './covers/Donkey Kong Country- Tropical Freeze.jpg' },
  { name: 'Doom', image: './covers/Days of Doom.jpg' },
  { name: 'Doom 64 v1.0.2', image: './covers/Doom 64.jpg' },
  { name: 'Dora Chie: Mini-Dora Ongakutai to 7-tsu no Chie (Brain Training) v1.1.0', image: './covers/Dora Chie- Mini-Dora Ongakutai to 7-tsu no Chie Brain Training.jpg' },
  { name: 'Dora Eigo: Nobita to Yousei no Fushigi Collection (English Training) v1.1.0', image: './covers/Dora Eigo- Nobita to Yousei no Fushigi Collection English Training.jpg' },
  { name: 'Dora Kazu: Nobita no Suuji Daibouken (Math Training) v1.1.0', image: './covers/Dora Kazu- Nobita no Suuji Daibouken Math Training.jpg' },
  { name: 'Doraemon Nobita Story of Seasons', image: './covers/Doraemon Story of Seasons.jpg' },
  { name: 'Doraemon Story of Seasons: Friends of the Great Kingdom', image: './covers/Doraemon Story of Seasons- Friends of the Great Kingdom.jpg' },
  { name: 'Double Dragon Gaiden: Rise of the Dragons v1.0.2', image: './covers/Double Dragon Gaiden- Rise of the Dragons.jpg' },
  { name: 'Dr Kawashima\'s Brain Training', image: './covers/Dr Kawashima\'s Brain Training.jpg' },
  { name: 'Dragon Quest Builders', image: './covers/Dragon Quest Builders.jpg' },
  { name: 'Dragon Quest Builders 2', image: './covers/Dragon Quest Builders 2.jpg' },
  { name: 'Dragon Quest Monsters: The Dark Prince v1.0.1', image: './covers/Dragon Quest Monsters- The Dark Prince.jpg' },
  { name: 'Dragon Quest Treasures', image: './covers/Dragon Quest Treasures.jpg' },
  { name: 'Dragon Quest III HD-2D Remake v1.0.1', image: './covers/Dragon Quest III HD-2D Remake.jpg' },
  { name: 'Dragon Quest XI S: Echoes of an Elusive Age - Definitive Edition', image: './covers/Dragon Quest XI S- Echoes of an Elusive Age - Definitive Edition.jpg' },
  { name: 'Dragon\'s Dogma: Dark Arisen', image: './covers/Dragon\'s Dogma- Dark Arisen.jpg' },
  { name: 'Dragon Ball FighterZ', image: './covers/Dragon Ball FighterZ.jpg' },
  { name: 'Dragon Ball Z: Kakarot + A New Power Awakens Set', image: './covers/Dragon Ball Z- Kakarot + A New Power Awakens Set.jpg' },
  { name: 'Dredge v1.0.1', image: './covers/Dredge.jpg' },
  { name: 'Dungeon of the Endless', image: './covers/Dungeon of the Endless.jpg' },
  { name: 'Dusk Diver 2', image: './covers/Dusk Diver 2.jpg' },
  { name: 'Dying Light: Platinum Edition', image: './covers/Dying Light- Platinum Edition.jpg' },
  { name: 'EA Sports FC 24', image: './covers/EA Sports FC 24.jpg' },
  { name: 'EA Sports FC 25', image: './covers/EA Sports FC 25.jpg' },
  { name: 'Eiyuden Chronicle: Hundred Heroes v1.01', image: './covers/Eiyuden Chronicle- Hundred Heroes.jpg' },
  { name: 'El Shaddai: Ascension of the Metatron HD Remaster', image: './covers/El Shaddai- Ascension of the Metatron HD Remaster.jpg' },
  { name: 'Emio - The Smiling Man: Famicom Detective Club', image: './covers/Emio - The Smiling Man- Famicom Detective Club.jpg' },
  { name: 'Ender Lilies: Quietus of the Knights v1.1.5b', image: './covers/Ender Lilies- Quietus of the Knights.jpg' },
  { name: 'Endless Ocean Luminous', image: './covers/Endless Ocean Luminous.jpg' },
  { name: 'Etrian Odyssey HD Remaster', image: './covers/Etrian Odyssey HD Remaster.jpg' },
  { name: 'Etrian Odyssey II HD Remaster', image: './covers/Etrian Odyssey II HD Remaster.jpg' },
  { name: 'Etrian Odyssey III HD Remaster', image: './covers/Etrian Odyssey III HD Remaster.jpg' },
  { name: 'Fairy Tail', image: './covers/Fairy Tail.jpg' },
  { name: 'Fantasy Friends', image: './covers/Fantasy Friends.jpg' },
  { name: 'Fashion Dreamer', image: './covers/Fashion Dreamer.jpg' },
  { name: 'Fatal Frame: Maiden of Black Water (Project Zero: Maiden of Black Water)', image: './covers/Fatal Frame- Maiden of Black Water (Project Zero- Maiden of Black Water).jpg' },
  { name: 'Fatal Frame: Mask of the Lunar Eclipse', image: './covers/Fatal Frame- Mask of the Lunar Eclipse.jpg' },
  { name: 'Fate/Extella Link', image: './covers/Fate-Extella Link.jpg' },
  { name: 'Fate/Extella: The Umbral Star', image: './covers/Fate-Extella- The Umbral Star.jpg' },
  { name: 'Fate/Samurai Remnant (Fate/stay night Remastered)', image: './covers/Fate Samurai Remnant Fate stay night Remastered.jpg' },
  { name: 'FIFA 21 Legacy Edition', image: './covers/FIFA 21 Legacy Edition.jpg' },
  { name: 'FIFA 22 Legacy Edition', image: './covers/FIFA 22 Legacy Edition.jpg' },
  { name: 'FIFA 23 Legacy Edition', image: './covers/FIFA 23 Legacy Edition.jpg' },
  { name: 'Final Fantasy VII v1.0.2_5', image: './covers/Final Fantasy VII.jpg' },
  { name: 'Final Fantasy VIII Remastered v1.0.1_5', image: './covers/Final Fantasy VIII Remastered.jpg' },
  { name: 'Final Fantasy X/X-2 HD Remaster', image: './covers/Final Fantasy X-X-2 HD Remaster.jpg' },
  { name: 'Final Fantasy XII: The Zodiac Age', image: './covers/Final Fantasy XII- The Zodiac Age.jpg' },
  { name: 'Fire Emblem Engage', image: './covers/Fire Emblem Engage.jpg' },
  { name: 'Fire Emblem: Three Houses', image: './covers/Fire Emblem- Three Houses.jpg' },
  { name: 'Fire Emblem Warriors', image: './covers/Fire Emblem Warriors.jpg' },
  { name: 'Fire Emblem Warriors: Three Hopes v1.0.1', image: './covers/Fire Emblem Warriors- Three Hopes.jpg' },
  { name: 'Fishing Star World Tour', image: './covers/Fishing Star World Tour.jpg' },
  { name: 'F.I.S.T.: Forged In Shadow Torch', image: './covers/F.I.S.T.- Forged In Shadow Torch.jpg' },
  { name: 'Fitness Boxing', image: './covers/Fitness Boxing 2- Rhythm & Exercise.jpg' },
  { name: 'Fitness Boxing feat. Hatsune Miku', image: './covers/Fitness Boxing feat. Hatsune Miku.jpg' },
  { name: 'Fitness Boxing: Fist of the North Star', image: './covers/Fitness Boxing- Fist of the North Star.jpg' },
  { name: 'Fitness Boxing 2: Rhythm & Exercise', image: './covers/Fitness Boxing 2- Rhythm & Exercise.jpg' },
  { name: 'Five Nights at Freddy\'s v1.0.1', image: './covers/Five Nights at Freddys.jpg' },
  { name: 'Five Nights at Freddy\'s 2 v1.0.3', image: './covers/Five Nights at Freddys 2.jpg' },
  { name: 'Five Nights at Freddy\'s 3 v1.0.1', image: './covers/Five Nights at Freddys 3.jpg' },
  { name: 'Five Nights at Freddy\'s 4 v1.0.2', image: './covers/Five Nights at Freddys 4.jpg' },
  { name: 'Five Nights at Freddy\'s: Sister Location v1.0.1', image: './covers/Five Nights at Freddys- Sister Location.jpg' },
  { name: 'Five Nights at Freddy\'s: Security Breach v0.3', image: './covers/Five Nights at Freddys- Security Breach.jpg' },
  { name: 'Game Builder Garage', image: './covers/Game Builder Garage.jpg' },
  { name: 'GetsuFumaDen v1.0.1', image: './covers/GetsuFumaDen.jpg' },
  { name: 'GetsuFumaDen: Undying Moon + DLC v1.1.1', image: './covers/GetsuFumaDen- Undying Moon.jpg' },
  { name: 'Ghost Trick: Phantom Detective', image: './covers/Ghost Trick- Phantom Detective.jpg' },
  { name: 'Ghostrunner', image: './covers/Ghostrunner.jpg' },
  { name: 'Giana Sisters: Twisted Dreams - Owltimate Edition', image: './covers/Giana Sisters- Twisted Dreams - Owltimate Edition.jpg' },
  { name: 'Goat Simulator 3 v1.0.7.1', image: './covers/Goat Simulator 3.jpg' },
  { name: 'God Eater 3', image: './covers/God Eater 3.jpg' },
  { name: 'Grand Theft Auto III - The Definitive Edition v1.0.4', image: './covers/Grand Theft Auto III - The Definitive Edition.jpg' },
  { name: 'Grand Theft Auto: Vice City - The Definitive Edition v1.0.1', image: './covers/Grand Theft Auto- Vice City - The Definitive Edition.jpg' },
  { name: 'Grand Theft Auto: San Andreas - The Definitive Edition v1.0.4', image: './covers/Grand Theft Auto- San Andreas - The Definitive Edition.jpg' },
  { name: 'Greak: Memories of Azur', image: './covers/Greak- Memories of Azur.jpg' },
  { name: 'Grip: Combat Racing', image: './covers/Grip- Combat Racing.jpg' },
  { name: 'Guacamelee! Super Turbo Championship Edition', image: './covers/Guacamelee! Super Turbo Championship Edition.jpg' },
  { name: 'Guacamelee! 2 v1.0.3', image: './covers/Guacamelee! 2.jpg' },
  { name: 'Guilty Gear', image: './covers/Guilty Gear.jpg' },
  { name: 'Guilty Gear XX Accent Core Plus R v1.0.1', image: './covers/Guilty Gear XX Accent Core Plus R.jpg' },
  { name: 'Gundam Breaker 4 v1.1.0', image: './covers/Gundam Breaker 4.jpg' },
  { name: 'Hades v1.0.37136', image: './covers/Hades.jpg' },
  { name: 'Hard West Ultimate Edition', image: './covers/Hard West Ultimate Edition.jpg' },
  { name: 'Hardcore Mecha + 6 DLC', image: './covers/Hardcore Mecha.jpg' },
  { name: 'Harvest Moon: The Winds of Anthos', image: './covers/Harvest Moon- The Winds of Anthos.jpg' },
  { name: 'Harvestella', image: './covers/Harvestella.jpg' },
  { name: 'Hatsune Miku: Project Diva Mega Mix (Hatsune Miku: Project Diva Mega39\'s)', image: './covers/Hatsune Miku- Project Diva Mega Mix (Hatsune Miku- Project Diva Mega39\'s).jpg' },
  { name: 'Hoa v1.0.4', image: './covers/Hoa.jpg' },
  { name: 'Hogwarts Legacy', image: './covers/Hogwarts Legacy.jpg' },
  { name: 'Hollow Knight v1.4.3.2', image: './covers/Hollow Knight.jpg' },
  { name: 'Hot Wheels Unleashed', image: './covers/Hot Wheels Unleashed.jpg' },
  { name: 'Human: Fall Flat v1.4.8', image: './covers/Human- Fall Flat.jpg' },
  { name: 'Hyrule Warriors: Age of Calamity v1.3.0', image: './covers/Hyrule Warriors- Age of Calamity.jpg' },
  { name: 'Hyrule Warriors: Definitive Edition', image: './covers/Hyrule Warriors- Definitive Edition.jpg' },
  { name: 'I am Setsuna', image: './covers/I am Setsuna.jpg' },
  { name: 'Immortals Fenyx Rising', image: './covers/Immortals Fenyx Rising.jpg' },
  { name: 'Infinity Strash: Dragon Quest The Adventure of Dai', image: './covers/Infinity Strash- Dragon Quest The Adventure of Dai.jpg' },
  { name: 'Into the Breach v1.2.75', image: './covers/Into the Breach.jpg' },
  { name: 'It Takes Two + 2 DLC', image: './covers/It Takes Two.jpg' },
  { name: 'Jack Jeanne', image: './covers/Jack Jeanne.jpg' },
  { name: 'Jump Force Deluxe Edition v1.02', image: './covers/Jump Force Deluxe Edition.jpg' },
  { name: 'Just Dance 2018', image: './covers/Just Dance 2018.jpg' },
  { name: 'Just Dance 2019 v290003.438003', image: './covers/Just Dance 2019.jpg' },
  { name: 'Just Dance 2020', image: './covers/Just Dance 2020.jpg' },
  { name: 'Just Dance 2021', image: './covers/Just Dance 2021.jpg' },
  { name: 'Just Dance 2022', image: './covers/Just Dance 2022.jpg' },
  { name: 'Kage: Shadow of The Ninja (Shadow of the Ninja - Reborn)', image: './covers/Kage- Shadow of The Ninja (Shadow of the Ninja – Reborn).jpg' },
  { name: 'Kao the Kangaroo', image: './covers/Kao the Kangaroo.jpg' },
  { name: 'Katana Kami: A Way of the Samurai Story', image: './covers/Katana Kami- A Way of the Samurai Story.jpg' },
  { name: 'KeyWe', image: './covers/KeyWe.jpg' },
  { name: 'Kingdom Come Deliverance: Royal Edition', image: './covers/Kingdom Come Deliverance- Royal Edition.jpg' },
  { name: 'Kingdom Hearts: Melody of Memory v1.01', image: './covers/Kingdom Hearts- Melody of Memory.jpg' },
  { name: 'Kingdom: New Lands v1.3.1b', image: './covers/Kingdom- New Lands.jpg' },
  { name: 'Kingdom Two Crowns v1.08b', image: './covers/Kingdom Two Crowns.jpg' },
  { name: 'Kingdoms of Amalur: Re-Reckoning', image: './covers/Kingdoms of Amalur- Re-Reckoning.jpg' },
  { name: 'Kirby and the Forgotten Land', image: './covers/Kirby and the Forgotten Land.jpg' },
  { name: 'Kirby Star Allies v3.0.0', image: './covers/Kirby Star Allies.jpg' },
  { name: 'Kirby\'s Return to Dream Land Deluxe', image: './covers/Kirby\'s Return to Dream Land Deluxe.jpg' },
  { name: 'Kitaria Fables', image: './covers/Kitaria Fables.jpg' },
  { name: 'Klonoa Phantasy Reverie Series', image: './covers/Klonoa Phantasy Reverie Series.jpg' },
  { name: 'Layers of Fear: Legacy v1.0.1', image: './covers/Layers of Fear- Legacy.jpg' },
  { name: 'Layton\'s Mystery Journey: Katrielle and the Millionaires\' Conspiracy Deluxe Edition', image: './covers/Laytons Mystery Journey- Katrielle and the Millionaires Conspiracy Deluxe Edition.jpg' },
  { name: 'Legend of Kay Anniversary', image: './covers/Legend of Kay Anniversary.jpg' },
  { name: 'LEGO City Undercover', image: './covers/LEGO City Undercover.jpg' },
  { name: 'LEGO DC Super-Villains', image: './covers/LEGO DC Super-Villains.jpg' },
  { name: 'LEGO Harry Potter Collection', image: './covers/LEGO Harry Potter Collection.jpg' },
  { name: 'LEGO Horizon Adventures', image: './covers/LEGO Horizon Adventures.jpg' },
  { name: 'LEGO Jurassic World', image: './covers/LEGO Jurassic World.jpg' },
  { name: 'LEGO Marvel Super Heroes', image: './covers/LEGO Marvel Super Heroes.jpg' },
  { name: 'LEGO Marvel Super Heroes 2', image: './covers/LEGO Marvel Super Heroes 2.jpg' },
  { name: 'LEGO Movie 2 Videogame, The', image: './covers/LEGO Movie 2 Videogame, The.jpg' },
  { name: 'LEGO Ninjago Movie Videogame, The', image: './covers/LEGO Ninjago Movie Videogame, The.jpg' },
  { name: 'LEGO Star Wars: The Skywalker Saga', image: './covers/LEGO Star Wars- The Skywalker Saga.jpg' },
  { name: 'LEGO The Incredibles', image: './covers/LEGO The Incredibles.jpg' },
  { name: 'LEGO Worlds', image: './covers/LEGO Worlds.jpg' },
  { name: 'LEGO 2K Drive v1.2', image: './covers/LEGO 2K Drive.jpg' },
  { name: 'Let\'s Get Fit', image: './covers/Lets Get Fit.jpg' },
  { name: 'Let\'s Sing 2024', image: './covers/Lets Sing 2024.jpg' },
  { name: 'Little Friends: Dogs & Cats', image: './covers/Little Friends- Dogs & Cats.jpg' },
  { name: 'Little Nightmares Complete Edition v1.0.2', image: './covers/Little Nightmares Complete Edition.jpg' },
  { name: 'Little Nightmares II', image: './covers/Little Nightmares II.jpg' },
  { name: 'Live A Live', image: './covers/Live A Live.jpg' },
  { name: 'L.O.L. Surprise! Movie Night', image: './covers/L.O.L. Surprise! Movie Night.jpg' },
  { name: 'Loop8: Summer of Gods', image: './covers/Loop8- Summer of Gods.jpg' },
  { name: 'Lost Sphear v1.1.0', image: './covers/Lost Sphear.jpg' },
  { name: 'LoveKami -Divinity Stage- v1.0.1', image: './covers/LoveKami -Divinity Stage-.jpg' },
  { name: 'LoveKami -Useless Goddess- v1.1.0', image: './covers/LoveKami -Useless Goddess-.jpg' },
  { name: 'LoveKami -Healing Harem- v1.0.1', image: './covers/LoveKami -Healing Harem-.jpg' },
  { name: 'Lovers in a Dangerous Spacetime v1.0.4', image: './covers/Lovers in a Dangerous Spacetime.jpg' },
  { name: 'Luigi\'s Mansion 2 HD', image: './covers/Luigis Mansion 2 HD.jpg' },
  { name: 'Luigi\'s Mansion 3 v1.2.1', image: './covers/Luigis Mansion 3.jpg' },
  { name: 'Maid of the Dead', image: './covers/Maid of the Dead.jpg' },
  { name: 'Maneater', image: './covers/Maneater.jpg' },
  { name: 'Mario & Luigi: Brothership', image: './covers/Mario & Luigi- Brothership.jpg' },
  { name: 'Mario & Sonic at the Olympic Games Tokyo 2020', image: './covers/Mario & Sonic at the Olympic Games Tokyo 2020.jpg' },
  { name: 'Mario Golf: Super Rush', image: './covers/Mario Golf- Super Rush.jpg' },
  { name: 'Mario Kart 8 Deluxe + DLC v2.4.0', image: './covers/Mario Kart 8 Deluxe.jpg' },
  { name: 'Mario Party Superstars v1.1.1', image: './covers/Mario Party Superstars.jpg' },
  { name: 'Mario + Rabbids Kingdom Battle', image: './covers/Mario + Rabbids Kingdom Battle.jpg' },
  { name: 'Mario + Rabbids Sparks of Hope', image: './covers/Mario + Rabbids Sparks of Hope.jpg' },
  { name: 'Mario Strikers: Battle League', image: './covers/Mario Strikers- Battle League.jpg' },
  { name: 'Mario Tennis Aces v3.1.0', image: './covers/Mario Tennis Aces.jpg' },
  { name: 'Mario vs. Donkey Kong', image: './covers/Mario vs. Donkey Kong.jpg' },
  { name: 'Marsupilami: Hoobadventure', image: './covers/Marsupilami- Hoobadventure.jpg' },
  { name: 'Marvel Ultimate Alliance 3: The Black Order', image: './covers/Marvel Ultimate Alliance 3- The Black Order.jpg' },
  { name: 'Master Detective Archives: Rain Code', image: './covers/Master Detective Archives- Rain Code.jpg' },
  { name: 'Mega Man 11', image: './covers/Mega Man 11.jpg' },
  { name: 'Mega Man Battle Network Legacy Collection Vol.1', image: './covers/Mega Man Battle Network Legacy Collection Vol.1.jpg' },
  { name: 'Mega Man Battle Network Legacy Collection Vol.2', image: './covers/Mega Man Battle Network Legacy Collection Vol.2.jpg' },
  { name: 'Mega Man Zero/ZX Legacy Collection', image: './covers/Mega Man Zero-ZX Legacy Collection.jpg' },
  { name: 'Megadimension Neptunia VII', image: './covers/Megadimension Neptunia VII.jpg' },
  { name: 'Memories Off 1 v1.0.1', image: './covers/Memories Off 1.jpg' },
  { name: 'Memories Off 2 v1.0.1', image: './covers/Memories Off 2.jpg' },
  { name: 'Memories Off 3: Omoide ni Kawaru Kimi v1.0.1', image: './covers/Memories Off 3- Omoide ni Kawaru Kimi.jpg' },
  { name: 'Memories Off: Sorekara v1.0.1', image: './covers/Memories Off- Sorekara.jpg' },
  { name: 'Memories Off 5: Togireta Film', image: './covers/Memories Off 5- Togireta Film.jpg' },
  { name: 'Memories Off 6: T-wave', image: './covers/Memories Off 6- T-wave.jpg' },
  { name: 'Memories Off: Yubikiri no Kioku', image: './covers/Memories Off- Yubikiri no Kioku.jpg' },
  { name: 'Memories Off -Innocent Fille-', image: './covers/Memories Off -Innocent Fille- for Dearest.jpg' },
  { name: 'Memories Off -Innocent Fille- for Dearest', image: './covers/Memories Off -Innocent Fille- for Dearest.jpg' },
  { name: 'Metal Gear Solid - Master Collection Version v1.1.1', image: './covers/Metal Gear Solid - Master Collection Version.jpg' },
  { name: 'Metal Gear Solid 2: Sons of Liberty - Master Collection Version v1.1.1', image: './covers/Metal Gear Solid 2- Sons of Liberty - Master Collection Version.jpg' },
  { name: 'Metal Gear Solid 3: Snake Eater - Master Collection Version v1.1.2', image: './covers/Metal Gear Solid 3- Snake Eater - Master Collection Version.jpg' },
  { name: 'Metal Gear & Metal Gear 2: Solid Snake v1.1.2', image: './covers/Metal Gear & Metal Gear 2- Solid Snake.jpg' },
  { name: 'Metroid Dread', image: './covers/Metroid Dread.jpg' },
  { name: 'Metroid Prime Remastered', image: './covers/Metroid Prime Remastered.jpg' },
  { name: 'Miitopia v1.0.3', image: './covers/Miitopia.jpg' },
  { name: 'Minecraft v1.2.12.0', image: './covers/Minecraft.jpg' },
  { name: 'Minecraft Dungeons + 7 DLC v1.10.4.0', image: './covers/Minecraft Dungeons.jpg' },
  { name: 'MLB The Show 23', image: './covers/MLB The Show 23.jpg' },
  { name: 'MLB The Show 24', image: './covers/MLB The Show 24.jpg' },
  { name: 'Moero Crystal H', image: './covers/Moero Crystal H.jpg' },
  { name: 'Monopoly v1.0.5', image: './covers/Monopoly.jpg' },
  { name: 'Monopoly Madness', image: './covers/Monopoly Madness.jpg' },
  { name: 'Monster Boy and the Cursed Kingdom v1.0.1', image: './covers/Monster Boy and the Cursed Kingdom.jpg' },
  { name: 'Monster Hunter Generations Ultimate', image: './covers/Monster Hunter Generations Ultimate.jpg' },
  { name: 'Monster Hunter: Rise', image: './covers/Monster Hunter- Rise.jpg' },
  { name: 'Monster Hunter Stories 2: Wings of Ruin v1.0.1', image: './covers/Monster Hunter Stories 2- Wings of Ruin.jpg' },
  { name: 'Monster Hunter XX: Double Cross', image: './covers/Monster Hunter XX- Double Cross.jpg' },
  { name: 'Moonlighter v1.0.0.1', image: './covers/Moonlighter.jpg' },
  { name: 'Mortal Kombat 11', image: './covers/Mortal Kombat 11.jpg' },
  { name: 'Moving Out 2', image: './covers/Moving Out 2.jpg' },
  { name: 'Mutant Football League: Dynasty Edition', image: './covers/Mutant Football League- Dynasty Edition.jpg' },
  { name: 'My Friend Peppa Pig', image: './covers/My Friend Peppa Pig.jpg' },
  { name: 'My Girlfriend is a Mermaid!?', image: './covers/My Girlfriend is a Mermaid.jpg' },
  { name: 'My Hero One\'s Justice', image: './covers/My Hero One\'s Justice.jpg' },
  { name: 'My Hero One\'s Justice 2', image: './covers/My Hero One\'s Justice 2.jpg' },
  { name: 'My Little Pony: A Maretime Bay Adventure', image: './covers/My Little Pony- A Maretime Bay Adventure.jpg' },
  { name: 'My Little Pony: A Zephyr Heights Mystery', image: './covers/My Little Pony- A Zephyr Heights Mystery.jpg' },
  { name: 'My Next Life as a Villainess: All Routes Lead to Doom! -Pirates of the Disturbance-', image: './covers/My Next Life as a Villainess- All Routes Lead to Doom! -Pirates of the Disturbance-.jpg' },
  { name: 'Naruto Shippuden: Ultimate Ninja Storm 4 - Road to Boruto', image: './covers/Naruto Shippuden- Ultimate Ninja Storm 4 - Road to Boruto.jpg' },
  { name: 'Naruto X Boruto: Ultimate Ninja Storm Connections', image: './covers/Naruto X Boruto- Ultimate Ninja Storm Connections.jpg' },
  { name: 'Natsu-Mon: 20th Century Summer Kid', image: './covers/Natsu-Mon- 20th Century Summer Kid.jpg' },
  { name: 'NBA 2K Playgrounds 2', image: './covers/NBA 2K Playgrounds 2.jpg' },
  { name: 'NBA 2K21', image: './covers/NBA 2K21.jpg' },
  { name: 'NBA 2K23', image: './covers/NBA 2K23.jpg' },
  { name: 'NBA 2K24 Kobe Bryant Edition', image: './covers/NBA 2K24 Kobe Bryant Edition.jpg' },
  { name: 'NBA 2K25', image: './covers/NBA 2K25.jpg' },
  { name: 'Need for Speed: Hot Pursuit Remastered', image: './covers/Need for Speed- Hot Pursuit Remastered.jpg' },
  { name: 'Nerf Legends', image: './covers/Nerf Legends.jpg' },
  { name: 'New Pokémon Snap', image: './covers/New Pokémon Snap.jpg' },
  { name: 'New Super Lucky\'s Tale', image: './covers/New Super Lucky\'s Tale.jpg' },
  { name: 'New Super Mario Bros. U Deluxe', image: './covers/New Super Mario Bros. U Deluxe.jpg' },
  { name: 'Nickelodeon Kart Racers 3: Slime Speedway', image: './covers/Nickelodeon Kart Racers 3- Slime Speedway.jpg' },
  { name: 'NieR: Automata The End of YoRHa Edition v1.0.2', image: './covers/NieR- Automata The End of YoRHa Edition.jpg' },
  { name: 'Ninja Gaiden Sigma', image: './covers/Ninja Gaiden Sigma.jpg' },
  { name: 'Ninja Gaiden Sigma 2', image: './covers/Ninja Gaiden Sigma 2.jpg' },
  { name: 'Ninja Gaiden 3: Razor\'s Edge', image: './covers/Ninja Gaiden 3- Razor\'s Edge.jpg' },
  { name: 'Nintendo Switch Sports v1.4.0', image: './covers/Nintendo Switch Sports.jpg' },
  { name: 'No Man\'s Sky', image: './covers/No Man\'s Sky.jpg' },
  { name: 'No More Heroes', image: './covers/No More Heroes.jpg' },
  { name: 'No More Heroes 2: Desperate Struggle', image: './covers/No More Heroes 2- Desperate Struggle.jpg' },
  { name: 'Octopath Traveler v1.0.3', image: './covers/Octopath Traveler.jpg' },
  { name: 'Octopath Traveler II', image: './covers/Octopath Traveler II.jpg' },
  { name: 'Omori', image: './covers/Omori.jpg' },
  { name: 'One Piece: Pirate Warriors 4', image: './covers/One Piece- Pirate Warriors 4.jpg' },
  { name: 'One Piece: Unlimited World Red Deluxe Edition', image: './covers/One Piece- Unlimited World Red Deluxe Edition.jpg' },
  { name: 'Onimusha: Warlords', image: './covers/Onimusha- Warlords.jpg' },
  { name: 'Oninaki', image: './covers/Oninaki.jpg' },
  { name: 'Ori and the Blind Forest: Definitive Edition v1.0.2', image: './covers/Ori and the Blind Forest- Definitive Edition.jpg' },
  { name: 'Ori and the Will of the Wisps v1.2.0', image: './covers/Ori and the Will of the Wisps.jpg' },
  { name: 'Overcooked! 2 v1.0.4', image: './covers/Overcooked! 2.jpg' },
  { name: 'Overcooked! All You Can Eat v1.0.1', image: './covers/Overcooked! All You Can Eat.jpg' },
  { name: 'Override 2: Super Mech League', image: './covers/Override 2- Super Mech League.jpg' },
  { name: 'Paper Mario: The Origami King', image: './covers/Paper Mario- The Origami King.jpg' },
  { name: 'Paper Mario: The Thousand-Year Door', image: './covers/Paper Mario- The Thousand-Year Door.jpg' },
  { name: 'PAW Patrol: Grand Prix v1.0.1', image: './covers/PAW Patrol- Grand Prix.jpg' },
  { name: 'PAW Patrol: Mighty Pups Save Adventure Bay!', image: './covers/PAW Patrol- Mighty Pups Save Adventure Bay!.jpg' },
  { name: 'PAW Patrol: On a Roll!', image: './covers/PAW Patrol- On a Roll!.jpg' },
  { name: 'PAW Patrol The Movie: Adventure City Calls v1.3.0', image: './covers/PAW Patrol The Movie- Adventure City Calls.jpg' },
  { name: 'PAW Patrol World', image: './covers/PAW Patrol World.jpg' },
  { name: 'Persona 4 Golden v1.0.2', image: './covers/Persona 4 Golden.jpg' },
  { name: 'Persona 5 Royal', image: './covers/Persona 5 Royal.jpg' },
  { name: 'Persona 5 Strikers', image: './covers/Persona 5 Strikers.jpg' },
  { name: 'Persona 5 Tactica', image: './covers/Persona 5 Tactica.jpg' },
  { name: 'Phoenix Wright: Ace Attorney Trilogy', image: './covers/Phoenix Wright- Ace Attorney Trilogy.jpg' },
  { name: 'Pikmin 1 + Pikmin 2', image: './covers/Pikmin 1-2.jpg' },
  { name: 'Pikmin 3 Deluxe', image: './covers/Pikmin 3 Deluxe.jpg' },
  { name: 'Pikmin 4 v1.0.1', image: './covers/Pikmin 4.jpg' },
  { name: 'Piofiore no Banshou -ricordo-', image: './covers/Piofiore no Banshou -ricordo-.jpg' },
  { name: 'Plants vs. Zombies: Battle for Neighborville Complete Edition', image: './covers/Plants vs. Zombies- Battle for Neighborville Complete Edition.jpg' },
  { name: 'Pokémon Brilliant Diamond v1.1.2', image: './covers/Pokémon Brilliant Diamond.jpg' },
  { name: 'Pokémon Legends: Arceus v1.0.1', image: './covers/Pokémon Legends- Arceus.jpg' },
  { name: 'Pokémon: Let\'s Go, Eevee!', image: './covers/Pokémon- Lets Go, Eevee!.jpg' },
  { name: 'Pokémon: Let\'s Go, Pikachu!', image: './covers/Pokémon- Lets Go, Pikachu!.jpg' },
  { name: 'Pokémon Mystery Dungeon: Rescue Team DX v1.0.1', image: './covers/Pokémon Mystery Dungeon- Rescue Team DX.jpg' },
  { name: 'Pokémon Scarlet + 2 DLC v3.0.0', image: './covers/Pokémon Scarlet.jpg' },
  { name: 'Pokémon Shield + 2 DLC v1.3.0', image: './covers/Pokémon Shield.jpg' },
  { name: 'Pokémon Shining Pearl', image: './covers/Pokémon Shining Pearl.jpg' },
  { name: 'Pokémon Sword + 2 DLC v1.3.0', image: './covers/Pokémon Sword.jpg' },
  { name: 'Pokémon Violet + 2 DLC v2.0.1', image: './covers/Pokémon Violet.jpg' },
  { name: 'Pokkén Tournament DX', image: './covers/Pokkén Tournament DX.jpg' },
  { name: 'Potion Permit', image: './covers/Potion Permit.jpg' },
  { name: 'Potionomics: Masterwork Edition', image: './covers/Potionomics- Masterwork Edition.jpg' },
  { name: 'Prince of Persia: The Lost Crown', image: './covers/Prince of Persia- The Lost Crown.jpg' },
  { name: 'Princess Peach: Showtime!', image: './covers/Princess Peach- Showtime!.jpg' },
  { name: 'Prinny: Can I Really Be the Hero? v1.0.1', image: './covers/Prinny- Can I Really Be the Hero.jpg' },
  { name: 'Prinny 2: Dawn of Operation Panties, Dood!', image: './covers/Prinny 2- Dawn of Operation Panties, Dood!.jpg' },
  { name: 'Puyo Puyo Tetris 2', image: './covers/Puyo Puyo Tetris 2.jpg' },
  { name: 'Puzzle Bobble Everybubble!', image: './covers/Puzzle Bobble Everybubble!.jpg' },
  { name: 'Rabbids: Party of Legends v1.0.1', image: './covers/Rabbids- Party of Legends.jpg' },
  { name: 'Rain on Your Parade + DLC v1.2.8', image: './covers/Rain on Your Parade.jpg' },
  { name: 'Rayman Legends Definitive Edition', image: './covers/Rayman Legends Definitive Edition.jpg' },
  { name: 'Re:Zero -Starting Life in Another World- The Prophecy of the Throne', image: './covers/Re-Zero -Starting Life in Another World- The Prophecy of the Throne.jpg' },
  { name: 'Red Dead Redemption', image: './covers/Red Dead Redemption.jpg' },
  { name: 'Resident Evil 0', image: './covers/Resident Evil 0.jpg' },
  { name: 'Resident Evil 4', image: './covers/Resident Evil 4.jpg' },
  { name: 'Resident Evil: Revelations', image: './covers/Resident Evil- Revelations.jpg' },
  { name: 'Ring Fit Adventure v1.2.0', image: './covers/Ring Fit Adventure.jpg' },
  { name: 'Risk of Rain v1.0.3', image: './covers/Risk of Rain.jpg' },
  { name: 'Risk of Rain 2 v1.0.1', image: './covers/Risk of Rain 2.jpg' },
  { name: 'River City Saga: Three Kingdoms', image: './covers/River City Saga- Three Kingdoms.jpg' },
  { name: 'Road 96 v1.01', image: './covers/Road 96.jpg' },
  { name: 'Romancing SaGa 2: Revenge of the Seven', image: './covers/Romancing SaGa 2- Revenge of the Seven.jpg' },
  { name: 'Romancing SaGa 3', image: './covers/Romancing SaGa 3.jpg' },
  { name: 'Root Letter: Last Answer', image: './covers/Root Letter- Last Answer.jpg' },
  { name: 'RPG Maker With', image: './covers/RPG Maker With.jpg' },
  { name: 'Rune Factory 3 Special', image: './covers/Rune Factory 3 Special.jpg' },
  { name: 'Rune Factory 5', image: './covers/Rune Factory 5.jpg' },
  { name: 'Sakuna: Of Rice and Ruin', image: './covers/Sakuna- Of Rice and Ruin.jpg' },
  { name: 'Salt and Sanctuary v1.0.1', image: './covers/Salt and Sanctuary.jpg' },
  { name: 'Samurai Jack: Battle Through Time v1.0.4', image: './covers/Samurai Jack- Battle Through Time.jpg' },
  { name: 'Samurai Shodown (Samurai Spirits)', image: './covers/Samurai Shodown (Samurai Spirits).jpg' },
  { name: 'Samurai Shodown NeoGeo Collection v1.0.1', image: './covers/Samurai Shodown NeoGeo Collection.jpg' },
  { name: 'Sangokushi 8 Remake (Romance of the Three Kingdoms 8 Remake)', image: './covers/Sangokushi 8 Remake (Romance of the Three Kingdoms 8 Remake).jpg' },
  { name: 'Sangokushi 13 with Power Up Kit + DLC (Romance of the Three Kingdoms XIII)', image: './covers/Sangokushi 13 with Power Up Kit.jpg' },
  { name: 'Sayonara Wild Hearts v1.2.0', image: './covers/Sayonara Wild Hearts.jpg' },
  { name: 'SD Gundam Battle Alliance', image: './covers/SD Gundam Battle Alliance.jpg' },
  { name: 'SD Gundam G Generation Cross Rays', image: './covers/SD Gundam G Generation Cross Rays.jpg' },
  { name: 'Sea of Stars v1.0.46981', image: './covers/Sea of Stars.jpg' },
  { name: 'SeaBed', image: './covers/SeaBed.jpg' },
  { name: 'Serious Sam Collection v1.2.0', image: './covers/Serious Sam Collection.jpg' },
  { name: 'Shadowverse: Champion\'s Battle', image: './covers/Shadowverse- Champion\'s Battle.jpg' },
  { name: 'Shin-chan: Me and the Professor on Summer Vacation -The Endless Seven-Day Journey-', image: './covers/Shin-chan- Me and the Professor on Summer Vacation -The Endless Seven-Day Journey-.jpg' },
  { name: 'Shin-chan: Shiro and the Coal Town v1.0.1', image: './covers/Shin-chan- Shiro and the Coal Town.jpg' },
  { name: 'Shin Megami Tensei V: Vengeance', image: './covers/Shin Megami Tensei V- Vengeance.jpg' },
  { name: 'Shin Sangoku Musou 7 with Moushouden DX (Dynasty Warriors 8- Xtreme Legends)', image: './covers/Shin Sangoku Musou 7 with Moushouden DX Dynasty Warriors 8- Xtreme Legends.jpg' },
  { name: 'Shin Sangoku Musou 8 Empires (Dynasty Warriors 9)', image: './covers/Shin Sangoku Musou 8 Empires (Dynasty Warriors 9).jpg' },
  { name: 'Shiren the Wanderer: The Mystery Dungeon of Serpentcoil Island', image: './covers/Shiren the Wanderer- The Mystery Dungeon of Serpentcoil Island.jpg' },
  { name: 'Shovel Knight: Treasure Trove v4.0A', image: './covers/Shovel Knight- Treasure Trove.jpg' },
  { name: 'Sid Meier\'s Civilization VI', image: './covers/Sid Meier\'s Civilization VI.jpg' },
  { name: 'Sifu v1.11_790', image: './covers/Sifu.jpg' },
  { name: 'SINce Memories: Off the Starry Sky', image: './covers/SINce Memories- Off the Starry Sky.jpg' },
  { name: 'Skabma - Snowfall', image: './covers/Skabma - Snowfall.jpg' },
  { name: 'Skull Island: Rise of Kong', image: './covers/Skull Island- Rise of Kong.jpg' },
  { name: 'Slay the Spire', image: './covers/Slay the Spire.jpg' },
  { name: 'Snack World: The Dungeon Crawl - Gold', image: './covers/Snack World- The Dungeon Crawl - Gold.jpg' },
  { name: 'Sniper Elite 3 Ultimate Edition', image: './covers/Sniper Elite 3 Ultimate Edition.jpg' },
  { name: 'Sniper Elite 4', image: './covers/Sniper Elite 4.jpg' },
  { name: 'Snipperclips Plus: Cut It Out, Together! v1.1.0', image: './covers/Snipperclips Plus- Cut It Out, Together!.jpg' },
  { name: 'SNK Heroines Tag Team Frenzy', image: './covers/SNK Heroines Tag Team Frenzy.jpg' },
  { name: 'Snow Bros. Nick & Tom Special + DLC v1.0.2', image: './covers/Snow Bros. Nick & Tom Special.jpg' },
  { name: 'SnowRunner', image: './covers/SnowRunner.jpg' },
  { name: 'Some Some Convenience Store v1.0.4', image: './covers/Some Some Convenience Store.jpg' },
  { name: 'Sonic Forces', image: './covers/Sonic Forces.jpg' },
  { name: 'Sonic Frontiers', image: './covers/Sonic Frontiers.jpg' },
  { name: 'Sonic Mania v1.04', image: './covers/Sonic Mania.jpg' },
  { name: 'Team Sonic Racing', image: './covers/Team Sonic Racing.jpg' },
  { name: 'Sonic X Shadow Generations', image: './covers/Sonic X Shadow Generations.jpg' },
  { name: 'Space Invaders Forever', image: './covers/Space Invaders Forever.jpg' },
  { name: 'Arkanoid vs Space Invaders', image: './covers/Arkanoid vs Space Invaders.jpg' },
  { name: 'Spiritfarer v1.14', image: './covers/Spiritfarer.jpg' },
  { name: 'Splatoon 2', image: './covers/Splatoon 2.jpg' },
  { name: 'Splatoon 3', image: './covers/Splatoon 3.jpg' },
  { name: 'SpongeBob SquarePants: Battle for Bikini Bottom - Rehydrated', image: './covers/SpongeBob SquarePants- Battle for Bikini Bottom – Rehydrated.jpg' },
  { name: 'SpongeBob SquarePants: Krusty Cook-Off Extra Krusty Edition + 2 DLC v1.1.1', image: './covers/SpongeBob SquarePants- Krusty Cook-Off Extra Krusty Edition.jpg' },
  { name: 'SpongeBob SquarePants: The Cosmic Shake', image: './covers/SpongeBob SquarePants- The Cosmic Shake.jpg' },
  { name: 'Sports Party', image: './covers/Sports Party.jpg' },
  { name: 'Spy x Family: Operation Diary (Spy x Anya: Operation Memories)', image: './covers/Spy x Family- Operation Diary Spy x Anya- Operation Memories.jpg' },
  { name: 'Spyro Reignited Trilogy', image: './covers/Spyro Reignited Trilogy.jpg' },
  { name: 'Star Ocean: The Second Story R', image: './covers/Star Ocean- The Second Story R.jpg' },
  { name: 'Star Wars: The Force Unleashed v1.0.3', image: './covers/Star Wars- The Force Unleashed.jpg' },
  { name: 'Star Wars Jedi Knight: Jedi Academy v1.0.5', image: './covers/Star Wars Jedi Knight- Jedi Academy.jpg' },
  { name: 'Star Wars Jedi Knight II: Jedi Outcast v1.0.5', image: './covers/Star Wars Jedi Knight II- Jedi Outcast.jpg' },
  { name: 'Star Wars: Knights of the Old Republic', image: './covers/Star Wars- Knights of the Old Republic.jpg' },
  { name: 'Star Wars: Knights of the Old Republic II - The Sith Lords', image: './covers/Star Wars- Knights of the Old Republic II - The Sith Lords.jpg' },
  { name: 'Star Wars Episode I: Racer v1.0.4', image: './covers/Star Wars Episode I- Racer.jpg' },
  { name: 'Star Wars: Republic Commando v1.0.4', image: './covers/Star Wars- Republic Commando.jpg' },
  { name: 'Stardew Valley v1.5.4.2', image: './covers/Stardew Valley.jpg' },
  { name: 'Steins;Gate Elite', image: './covers/Steins;Gate Elite.jpg' },
  { name: 'Steven Universe: Save the Light', image: './covers/Steven Universe- Save the Light.jpg' },
  { name: 'OK K.O.! Let\'s Play Heroes', image: './covers/OK K.O.! Let\'s Play Heroes.jpg' },
  { name: 'Story of Seasons: Friends of Mineral Town', image: './covers/Story of Seasons- Friends of Mineral Town.jpg' },
  { name: 'Story of Seasons: Pioneers of Olive Town', image: './covers/Story of Seasons- Pioneers of Olive Town.jpg' },
  { name: 'Street Fighter 30th Anniversary Collection', image: './covers/Street Fighter 30th Anniversary Collection.jpg' },
  { name: 'Streets of Rage 4 + DLC (Bare Knuckle IV)', image: './covers/Streets of Rage 4.jpg' },
  { name: 'Subnautica', image: './covers/Subnautica- Below Zero.jpg' },
  { name: 'Subnautica: Below Zero', image: './covers/Subnautica- Below Zero.jpg' },
  { name: 'Sumikko Gurashi: Sumikko Park he Youkoso', image: './covers/Sumikko Gurashi- Sumikko Park he Youkoso.jpg' },
  { name: 'Super Bomberman R v1.4.2', image: './covers/Super Bomberman R.jpg' },
  { name: 'Super Mario 3D All-Stars 1.0.1', image: './covers/Super Mario 3D All-Stars.jpg' },
  { name: 'Super Mario 3D World + Bowser\'s Fury v1.1.0', image: './covers/Super Mario 3D World + Bowser\'s Fury.jpg' },
  { name: 'Super Mario Bros. Wonder 1.0.1', image: './covers/Super Mario Bros. Wonder.jpg' },
  { name: 'Super Mario Maker 2 v3.0.2', image: './covers/Super Mario Maker 2.jpg' },
  { name: 'Super Mario Odyssey v1.3.0', image: './covers/Super Mario Odyssey.jpg' },
  { name: 'Super Mario Party v1.1.0', image: './covers/Super Mario Party.jpg' },
  { name: 'Super Mario Party Jamboree', image: './covers/Super Mario Party Jamboree.jpg' },
  { name: 'Super Mario RPG: Legend of the Seven Stars', image: './covers/Super Mario RPG- Legend of the Seven Stars.jpg' },
  { name: 'Super Robot Wars 30', image: './covers/Super Robot Wars 30.jpg' },
  { name: 'Super Robot Wars T', image: './covers/Super Robot Wars T.jpg' },
  { name: 'Super Robot Wars V', image: './covers/Super Robot Wars V.jpg' },
  { name: 'Super Smash Bros. Ultimate v2.0.1', image: './covers/Super Smash Bros. Ultimate.jpg' },
  { name: 'Super Street: Racer', image: './covers/Super Street- Racer.jpg' },
  { name: 'Super Zangyura v1.0.6', image: './covers/Super Zangyura.jpg' },
  { name: 'Surviving the Aftermath v1.20.1', image: './covers/Surviving the Aftermath.jpg' },
  { name: 'Sushi Striker: The Way of Sushido', image: './covers/Sushi Striker- The Way of Sushido.jpg' },
  { name: 'Sword Art Online: Alicization Lycoris', image: './covers/Sword Art Online- Alicization Lycoris.jpg' },
  { name: 'Sword Art Online: Fatal Bullet Complete Edition', image: './covers/Sword Art Online- Fatal Bullet Complete Edition.jpg' },
  { name: 'Sword Art Online: Hollow Realization Deluxe Edition', image: './covers/Sword Art Online- Hollow Realization Deluxe Edition.jpg' },
  { name: 'Tactics Ogre: Reborn v1.0.1', image: './covers/Tactics Ogre- Reborn.jpg' },
  { name: 'Taiko no Tatsujin: Drum \'n\' Fun!', image: './covers/Taiko no Tatsujin- Drum \'n\' Fun!.jpg' },
  { name: 'Taiko no Tatsujin: Rhythmic Adventure Pack', image: './covers/Taiko no Tatsujin- Rhythmic Adventure Pack.jpg' },
  { name: 'Taiko no Tatsujin: Rhythm Festival', image: './covers/Taiko no Tatsujin- Rhythm Festival.jpg' },
  { name: 'Taiko Risshiden V DX', image: './covers/Taiko Risshiden V DX.jpg' },
  { name: 'Tales of Vesperia: Definitive Edition', image: './covers/Tales of Vesperia- Definitive Edition.jpg' },
  { name: 'Taxi Chaos', image: './covers/Taxi Chaos.jpg' },
  { name: 'Teenage Mutant Ninja Turtles: Shredder\'s Revenge + DLC v1.0.7', image: './covers/Teenage Mutant Ninja Turtles- Shredder\'s Revenge.jpg' },
  { name: 'Teenage Mutant Ninja Turtles: The Cowabunga Collection', image: './covers/Teenage Mutant Ninja Turtles- The Cowabunga Collection.jpg' },
  { name: 'Temtem', image: './covers/Temtem.jpg' },
  { name: 'Terraria v1.0.3', image: './covers/Terraria.jpg' },
  { name: 'The Banner Saga Trilogy', image: './covers/The Banner Saga Trilogy.jpg' },
  { name: 'The Battle Cats Unite! + 3 DLC', image: './covers/The Battle Cats Unite!.jpg' },
  { name: 'The Binding of Isaac: Repentance', image: './covers/The Binding of Isaac- Repentance.jpg' },
  { name: 'The Caligula Effect 2', image: './covers/The Caligula Effect 2.jpg' },
  { name: 'The Company Man', image: './covers/The Company Man.jpg' },
  { name: 'The DioField Chronicle', image: './covers/The DioField Chronicle.jpg' },
  { name: 'The Elder Scrolls V: Skyrim', image: './covers/The Elder Scrolls V- Skyrim.jpg' },
  { name: 'The House of the Dead: Remake v1.0.1', image: './covers/The House of the Dead- Remake.jpg' },
  { name: 'The King of Fighters XIII Global Match', image: './covers/The King of Fighters XIII Global Match.jpg' },
  { name: 'The Knight Witch v1.0.5', image: './covers/The Knight Witch.jpg' },
  { name: 'The Legend of Heroes: Ao no Kiseki: Kai', image: './covers/The Legend of Heroes- Ao no Kiseki- Kai.jpg' },
  { name: 'The Legend of Heroes: Hajimari no Kiseki', image: './covers/The Legend of Heroes- Hajimari no Kiseki.jpg' },
  { name: 'The Legend of Heroes: Sen no Kiseki I: Kai', image: './covers/The Legend of Heroes- Sen no Kiseki I- Kai.jpg' },
  { name: 'The Legend of Heroes: Sen no Kiseki II: Kai', image: './covers/The Legend of Heroes- Sen no Kiseki II- Kai.jpg' },
  { name: 'The Legend of Heroes: Sen no Kiseki III', image: './covers/The Legend of Heroes- Sen no Kiseki III.jpg' },
  { name: 'The Legend of Zelda: Breath of the Wild + 2 DLC v1.6.0', image: './covers/The Legend of Zelda- Breath of the Wild.jpg' },
  { name: 'The Legend of Zelda: Echoes of Wisdom', image: './covers/The Legend of Zelda- Echoes of Wisdom.jpg' },
  { name: 'The Legend of Zelda: Link\'s Awakening', image: './covers/The Legend of Zelda- Link\'s Awakening.jpg' },
  { name: 'The Legend of Zelda: Skyward Sword HD', image: './covers/The Legend of Zelda- Skyward Sword HD.jpg' },
  { name: 'The Legend of Zelda: Tears of the Kingdom', image: './covers/The Legend of Zelda- Tears of the Kingdom.jpg' },
  { name: 'The Messenger v2.0.0', image: './covers/The Messenger.jpg' },
  { name: 'The Pathless', image: './covers/The Pathless.jpg' },
  { name: 'The Survivalists', image: './covers/The Survivalists.jpg' },
  { name: 'The Walking Dead: The Final Season v1.0.2', image: './covers/The Walking Dead- The Final Season.jpg' },
  { name: 'The Witcher 3: Wild Hunt - Complete Edition', image: './covers/The Witcher 3- Wild Hunt - Complete Edition.jpg' },
  { name: 'The Wonderful 101: Remastered', image: './covers/The Wonderful 101- Remastered.jpg' },
  { name: 'Theatrhythm Final Bar Line v1.0.1', image: './covers/Theatrhythm Final Bar Line.jpg' },
  { name: 'Titan Quest', image: './covers/Titan Quest.jpg' },
  { name: 'Tokyo Mirage Sessions FE Encore', image: './covers/Tokyo Mirage Sessions FE Encore.jpg' },
  { name: 'Touhou Mystia\'s Izakaya', image: './covers/Touhou Mystia\'s Izakaya.jpg' },
  { name: 'Transformers: Battlegrounds', image: './covers/Transformers- Battlegrounds.jpg' },
  { name: 'Trials of Mana (Seiken Densetsu 3)', image: './covers/Trials of Mana (Seiken Densetsu 3).jpg' },
  { name: 'Triangle Strategy v1.0.1', image: './covers/Triangle Strategy.jpg' },
  { name: 'Trine 5: A Clockwork Conspiracy v1.0.1', image: './covers/Trine 5- A Clockwork Conspiracy.jpg' },
  { name: 'Trinity Trigger', image: './covers/Trinity Trigger.jpg' },
  { name: 'TT Isle of Man', image: './covers/TT Isle of Man.jpg' },
  { name: 'TT Isle of Man Ride on the Edge 2', image: './covers/TT Isle of Man Ride on the Edge 2.jpg' },
  { name: 'Tunic v1.0.3', image: './covers/Tunic.jpg' },
  { name: 'Two Point Campus', image: './covers/Two Point Campus.jpg' },
  { name: 'Two Point Hospital + 4 DLC v1.0.6', image: './covers/Two Point Hospital.jpg' },
  { name: 'Ultimate Chicken Horse v1.8.20', image: './covers/Ultimate Chicken Horse.jpg' },
  { name: 'Ultra Kaiju Monster Rancher', image: './covers/Ultra Kaiju Monster Rancher.jpg' },
  { name: 'Ultra Street Fighter II: The Final Challengers', image: './covers/Ultra Street Fighter II- The Final Challengers.jpg' },
  { name: 'Unbox: Newbie\'s Adventure', image: './covers/Unbox- Newbies Adventure.jpg' },
  { name: 'Uncharted Waters IV with Power-Up Kit HD Version', image: './covers/Uncharted Waters IV with Power-Up Kit HD Version.jpg' },
  { name: 'Under Night In-Birth II Sys:Celes', image: './covers/Under Night In-Birth II Sys-Celes.jpg' },
  { name: 'Undertale', image: './covers/Undertale.jpg' },
  { name: 'Unicorn Overlord', image: './covers/Unicorn Overlord.jpg' },
  { name: 'Unravel Two', image: './covers/Unravel Two.jpg' },
  { name: 'Untitled Goose Game v1.1.0', image: './covers/Untitled Goose Game.jpg' },
  { name: 'Victor Vran Overkill Edition', image: './covers/Victor Vran Overkill Edition.jpg' },
  { name: 'Virche Evermore -ErroR:salvation-', image: './covers/Virche Evermore -ErroR-salvation-.jpg' },
  { name: 'Wand of Fortune R', image: './covers/Wand of Fortune R.jpg' },
  { name: 'WarioWare: Get It Together!', image: './covers/WarioWare- Get It Together!.jpg' },
  { name: 'WarioWare: Move It!', image: './covers/WarioWare- Move It!.jpg' },
  { name: 'Warriors Orochi 4 Ultimate + DLC', image: './covers/Warriors Orochi 4 Ultimate.jpg' },
  { name: 'Who Wants to Be a Millionaire?', image: './covers/Who Wants to Be a Millionaire.jpg' },
  { name: 'Wild Card Football v1.0.1.0', image: './covers/Wild Card Football.jpg' },
  { name: 'Windstorm: An Unexpected Arrival', image: './covers/Windstorm- An Unexpected Arrival.jpg' },
  { name: 'Witch on the Holy Night', image: './covers/Witch on the Holy Night.jpg' },
  { name: 'Wolfenstein II: The New Colossus', image: './covers/Wolfenstein II- The New Colossus.jpg' },
  { name: 'Wonder Boy: The Dragon\'s Trap', image: './covers/Wonder Boy- The Dragon\'s Trap.jpg' },
  { name: 'WRC 8 FIA World Rally Championship', image: './covers/WRC 8 FIA World Rally Championship.jpg' },
  { name: 'WRC 9 FIA World Rally Championship', image: './covers/WRC 9 FIA World Rally Championship.jpg' },
  { name: 'WRC 10 FIA World Rally Championship', image: './covers/WRC 10 FIA World Rally Championship.jpg' },
  { name: 'WWE 2K18', image: './covers/WWE 2K18.jpg' },
  { name: 'Xenoblade Chronicles: Definitive Edition', image: './covers/Xenoblade Chronicles- Definitive Edition.jpg' },
  { name: 'Xenoblade Chronicles 2', image: './covers/Xenoblade Chronicles 2.jpg' },
  { name: 'Xenoblade Chronicles 2: Torna - The Golden Country', image: './covers/Xenoblade Chronicles 2- Torna - The Golden Country.jpg' },
  { name: 'Xenoblade Chronicles 3', image: './covers/Xenoblade Chronicles 3.jpg' },
  { name: 'Xuan Yuan Sword 7', image: './covers/Xuan Yuan Sword 7.jpg' },
  { name: 'Yomawari: The Long Night Collection', image: './covers/Yomawari- The Long Night Collection.jpg' },
  { name: 'Yo-Kai Watch 4++ + DLC', image: './covers/Yo-Kai Watch 4.jpg' },
  { name: 'Yooka-Laylee and the Impossible Lair', image: './covers/Yooka-Laylee and the Impossible Lair.jpg' },
  { name: 'Yoshi\'s Crafted World', image: './covers/Yoshi\'s Crafted World.jpg' },
  { name: 'Ys VIII: Lacrimosa of Dana', image: './covers/Ys VIII- Lacrimosa of Dana.jpg' },
  { name: 'Ys IX: Monstrum Nox', image: './covers/Ys IX- Monstrum Nox.jpg' },
  { name: 'Ys X: Nordics', image: './covers/Ys X- Nordics.jpg' },
  { name: 'Yuoni v1.0.4.2', image: './covers/Yuoni.jpg' },
  { name: 'Zombie Army 4: Dead War', image: './covers/Zombie Army 4- Dead War.jpg' },
  { name: 'Zumba Burn it Up!', image: './covers/Zumba Burn it Up!.jpg' }
];
