export const games = [
  { name: '1-2-Switch', image: './covers/1-2-Switch.png' },
  { name: '13 Sentinels: Aegis Rim', image: './covers/13 Sentinels Aegis Rim.jpg' },
  { name: '30-in-1 Game Collection', image: './covers/30-in-1 Game Collection.png' },
  { name: 'Ace Angler Fishing Spirits M', image: './covers/Ace Angler Fishing Spirits M.png' },
  { name: 'Ace Attorney Investigations Collection', image: './covers/Ace Attorney Investigations Collection.png' },
  { name: 'Ace Combat 7: Skies Unknown Deluxe Edition', image: './covers/Ace Combat 7: Skies Unknown Deluxe Edition.png' },
  { name: 'Advance Wars 1+2: Re-Boot Camp', image: './covers/Advance Wars 1+2: Re-Boot Camp.png' },
  { name: 'Afterimage', image: './covers/Afterimage.png' },
  { name: 'AI: The Somnium Files', image: './covers/AI: The Somnium Files.png' },
  { name: 'AI: The Somnium Files – nirvanA Initiative', image: './covers/AI: The Somnium Files – nirvanA Initiative.png' },
  { name: 'Alex Kidd in Miracle World DX', image: './covers/Alex Kidd in Miracle World DX.png' },
  { name: 'Alice Gear Aegis CS: Concerto of Simulatrix', image: './covers/Alice Gear Aegis CS: Concerto of Simulatrix.png' },
  { name: 'All-Star Fruit Racing', image: './covers/All-Star Fruit Racing.png' },
  { name: 'Animal Crossing: New Horizons', image: './covers/Animal Crossing: New Horizons.png' },
  { name: 'Another Code: Recollection', image: './covers/Another Code: Recollection.png' },
  { name: 'Apollo Justice: Ace Attorney Trilogy', image: './covers/Apollo Justice: Ace Attorney Trilogy.png' },
  { name: 'ARK: Survival Evolved', image: './covers/ARK: Survival Evolved.png' },
  { name: 'Arms', image: './covers/Arms.png' },
  { name: 'Assassin\'s Creed III: Remastered', image: './covers/Assassin\'s Creed III: Remastered.png' },
  { name: 'Assassin\'s Creed: The Ezio Collection', image: './covers/Assassin\'s Creed: The Ezio Collection.png' },
  { name: 'Assassin\'s Creed: The Rebel Collection', image: './covers/Assassin\'s Creed: The Rebel Collection.png' },
  { name: 'Astral Chain', image: './covers/Astral Chain.png' },
  { name: 'Astroneer', image: './covers/Astroneer.png' },
  { name: 'Attack on Titan 2: Final Battle', image: './covers/Attack on Titan 2: Final Battle.png' },
  { name: 'Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings', image: './covers/Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings.png' },
  { name: 'Atelier Ryza: Ever Darkness & the Secret Hideout', image: './covers/Atelier Ryza: Ever Darkness & the Secret Hideout.png' },
  { name: 'Atelier Ryza 2: Lost Legends & the Secret Fairy', image: './covers/Atelier Ryza 2: Lost Legends & the Secret Fairy.png' },
  { name: 'Atelier Ryza 3: Alchemist of the End & the Secret Key', image: './covers/Atelier Ryza 3: Alchemist of the End & the Secret Key.png' },
  { name: 'Atelier Sophie: The Alchemist of the Mysterious Book DX', image: './covers/Atelier Sophie: The Alchemist of the Mysterious Book DX.png' },
  { name: 'Atelier Sophie 2: The Alchemist of the Mysterious Dream', image: './covers/Atelier Sophie 2: The Alchemist of the Mysterious Dream.png' },
  { name: 'Avatar: The Last Airbender – Quest for Balance', image: './covers/Avatar: The Last Airbender – Quest for Balance.png' },
  { name: 'Azur Lane: Crosswave', image: './covers/Azur Lane: Crosswave.png' },
  { name: 'Azure Striker Gunvolt: Striker Pack', image: './covers/Azure Striker Gunvolt: Striker Pack.png' },
  { name: 'Azure Striker Gunvolt 3', image: './covers/Azure Striker Gunvolt 3.png' },
  { name: 'Bakugan: Champions of Vestroia', image: './covers/Bakugan: Champions of Vestroia.png' },
  { name: 'Balan Wonderworld', image: './covers/Balan Wonderworld.png' },
  { name: 'Balatro', image: './covers/Balatro.png' },
  { name: 'Battle Chasers: Nightwar', image: './covers/Battle Chasers: Nightwar.png' },
  { name: 'Bayonetta', image: './covers/Bayonetta.png' },
  { name: 'Bayonetta 2', image: './covers/Bayonetta 2.png' },
  { name: 'Bayonetta 3', image: './covers/Bayonetta 3.png' },
  { name: 'Bayonetta Origins: Cereza and the Lost Demon', image: './covers/Bayonetta Origins: Cereza and the Lost Demon.png' },
  { name: 'Bear & Breakfast', image: './covers/Bear & Breakfast.png' },
  { name: 'Beasties', image: './covers/Beasties.png' },
  { name: 'Big Brain Academy', image: './covers/Big Brain Academy.png' },
  { name: 'BioShock Remastered', image: './covers/BioShock Remastered.png' },
  { name: 'Birushana: Rising Flower of Genpei', image: './covers/Birushana: Rising Flower of Genpei.png' },
  { name: 'Blasphemous', image: './covers/Blasphemous.png' },
  { name: 'Blasphemous 2', image: './covers/Blasphemous 2.png' },
  { name: 'Bloodstained: Ritual of the Night', image: './covers/Bloodstained: Ritual of the Night.png' },
  { name: 'Bluey: The Videogame', image: './covers/Bluey: The Videogame.png' },
  { name: 'Borderlands: Game of the Year Edition', image: './covers/Borderlands: Game of the Year Edition.png' },
  { name: 'Borderlands 3 Ultimate Edition', image: './covers/Borderlands 3 Ultimate Edition.png' },
  { name: 'Bravely Default II', image: './covers/Bravely Default II.png' },
  { name: 'Brigandine: The Legend of Runersia', image: './covers/Brigandine: The Legend of Runersia.png' },
  { name: 'Brilliant and Brilliant, My Family Modern Era (Hanayaka Nari, Waga Ichizoku Modern Nostalgie)', image: './covers/Brilliant and Brilliant, My Family Modern Era (Hanayaka Nari, Waga Ichizoku Modern Nostalgie).png' },
  { name: 'Bubble Bobble 4 Friends: The Baron is Back!', image: './covers/Bubble Bobble 4 Friends: The Baron is Back!.png' },
  { name: 'Buddy Mission: Bond', image: './covers/Buddy Mission: Bond.png' },
  { name: 'Bunny Garden', image: './covers/Bunny Garden.png' },
  { name: 'Burnout Paradise Remastered', image: './covers/Burnout Paradise Remastered.png' },
  { name: 'Capcom Belt Action Collection', image: './covers/Capcom Belt Action Collection.png' },
  { name: 'Capcom Fighting Collection', image: './covers/Capcom Fighting Collection.png' },
  { name: 'Captain Toad: Treasure Tracker', image: './covers/Captain Toad: Treasure Tracker.png' },
  { name: 'Captain Tsubasa: Rise of New Champions', image: './covers/Captain Tsubasa: Rise of New Champions.png' },
  { name: 'Carnival Games', image: './covers/Carnival Games.png' },
  { name: 'Castle Crashers Remastered v1.0.5', image: './covers/Castle Crashers Remastered v1.0.5.png' },
  { name: 'Cat Quest v1.01', image: './covers/Cat Quest v1.01.png' },
  { name: 'Cat Quest II v1.0.4', image: './covers/Cat Quest II v1.0.4.png' },
  { name: 'Catherine: Full Body', image: './covers/Catherine: Full Body.png' },
  { name: 'Celeste v1.4.1.1', image: './covers/Celeste v1.4.1.1.png' },
  { name: 'Chef Life: A Restaurant Simulator', image: './covers/Chef Life: A Restaurant Simulator.png' },
  { name: 'Chocobo GP Lite + DLC v1.0.1', image: './covers/Chocobo GP Lite + DLC v1.0.1.png' },
  { name: 'Cities: Skylines v1.0.3.37670', image: './covers/Cities: Skylines v1.0.3.37670.png' },
  { name: 'Cloudpunk', image: './covers/Cloudpunk.png' },
  { name: 'Clubhouse Games: 51 Worldwide Classics v1.1.2', image: './covers/Clubhouse Games: 51 Worldwide Classics v1.1.2.png' },
  { name: 'Collection of Mana', image: './covers/Collection of Mana.png' },
  { name: 'Contra Anniversary Collection v1.1.0', image: './covers/Contra Anniversary Collection v1.1.0.png' },
  { name: 'Contra: Operation Galuga v1.0.876634', image: './covers/Contra: Operation Galuga v1.0.876634.png' },
  { name: 'Crash Bandicoot 4: It\'s About Time', image: './covers/Crash Bandicoot 4: It\'s About Time.png' },
  { name: 'Crash Bandicoot N. Sane Trilogy', image: './covers/Crash Bandicoot N. Sane Trilogy.png' },
  { name: 'Crash Team Racing Nitro-Fueled', image: './covers/Crash Team Racing Nitro-Fueled.png' },
  { name: 'Cris Tales', image: './covers/Cris Tales.png' },
  { name: 'Crisis Core: Final Fantasy VII Reunion', image: './covers/Crisis Core: Final Fantasy VII Reunion.png' },
  { name: 'Cruis\'n Blast v1.06', image: './covers/Cruis\'n Blast v1.06.png' },
  { name: 'Crypt of the NecroDancer', image: './covers/Crypt of the NecroDancer.png' },
  { name: 'Crysis Remastered', image: './covers/Crysis Remastered.png' },
  { name: 'Crystar', image: './covers/Crystar.png' },
  { name: 'Cult of the Lamb v1.2.6', image: './covers/Cult of the Lamb v1.2.6.png' },
  { name: 'Cuphead + DLC v1.3.4', image: './covers/Cuphead + DLC v1.3.4.png' },
  { name: 'Cupid Parasite', image: './covers/Cupid Parasite.png' },
  { name: 'Curse of the Sea Rats', image: './covers/Curse of the Sea Rats.png' },
  { name: 'Dance with Devils', image: './covers/Dance with Devils.png' },
  { name: 'Danganronpa: Trigger Happy Havoc Anniversary Edition', image: './covers/Danganronpa: Trigger Happy Havoc Anniversary Edition.png' },
  { name: 'Danganronpa 2: Goodbye Despair Anniversary Edition', image: './covers/Danganronpa 2: Goodbye Despair Anniversary Edition.png' },
  { name: 'Danganronpa V3: Killing Harmony Anniversary Edition', image: './covers/Danganronpa V3: Killing Harmony Anniversary Edition.png' },
  { name: 'Danganronpa S: Ultimate Summer Camp', image: './covers/Danganronpa S: Ultimate Summer Camp.png' },
  { name: 'Dark Souls: Remastered', image: './covers/Dark Souls: Remastered.png' },
  { name: 'Darksiders II Deathinitive Edition', image: './covers/Darksiders II Deathinitive Edition.png' },
  { name: 'Darksiders III', image: './covers/Darksiders III.png' },
  { name: 'Darksiders Warmastered Edition', image: './covers/Darksiders Warmastered Edition.png' },
  { name: 'Dave the Diver + DLC v1.0.2.651', image: './covers/Dave the Diver + DLC v1.0.2.651.png' },
  { name: 'Days of Doom', image: './covers/Days of Doom.png' },
  { name: 'DC Super Hero Girls: Teen Power', image: './covers/DC Super Hero Girls: Teen Power.png' },
  { name: 'DC\'s Justice League: Cosmic Chaos', image: './covers/DC\'s Justice League: Cosmic Chaos.png' },
  { name: 'Dead Cells + 5 DLC v1.23.1', image: './covers/Dead Cells + 5 DLC v1.23.1.png' },
  { name: 'Dead or Alive Xtreme 3 Scarlet + 11 DLC', image: './covers/Dead or Alive Xtreme 3 Scarlet + 11 DLC.png' },
  { name: 'Deadly Premonition 2: A Blessing In Disguise', image: './covers/Deadly Premonition 2: A Blessing In Disguise.png' },
  { name: 'Daemon X Machina', image: './covers/Daemon X Machina.png' },
  { name: 'Demon Slayer -Kimetsu no Yaiba- Sweep the Board!', image: './covers/Demon Slayer -Kimetsu no Yaiba- Sweep the Board!.png' },
  { name: 'Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles', image: './covers/Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles.png' },
  { name: 'Detective Pikachu Returns', image: './covers/Detective Pikachu Returns.png' },
  { name: 'Devil May Cry', image: './covers/Devil May Cry.png' },
  { name: 'Diablo III: Eternal Collection', image: './covers/Diablo III: Eternal Collection.png' },
  { name: 'Digimon Story: Cyber Sleuth Hacker\'s Memory', image: './covers/Digimon Story: Cyber Sleuth Hacker\'s Memory.png' },
  { name: 'Digimon Survive', image: './covers/Digimon Survive.png' },
  { name: 'Disco Elysium – The Final Cut v1.03', image: './covers/Disco Elysium – The Final Cut v1.03.png' },
  { name: 'Disgaea 4 Complete+', image: './covers/Disgaea 4 Complete+.png' },
  { name: 'Disgaea 5: Alliance of Vengeance', image: './covers/Disgaea 5: Alliance of Vengeance.png' },
  { name: 'Disgaea 6: Defiance of Destiny', image: './covers/Disgaea 6: Defiance of Destiny.png' },
  { name: 'Disney Classic Games: Aladdin and The Lion King + DLC v1.5.0', image: './covers/Disney Classic Games: Aladdin and The Lion King + DLC v1.5.0.png' },
  { name: 'Disney Illusion Island v1.0.1', image: './covers/Disney Illusion Island v1.0.1.png' },
  { name: 'Divinity: Original Sin 2 – Definitive Edition v1.0.3.1', image: './covers/Divinity: Original Sin 2 – Definitive Edition v1.0.3.1.png' },
  { name: 'Doki Doki Literature Club Plus! v1.0.3', image: './covers/Doki Doki Literature Club Plus! v1.0.3.png' },
  { name: 'Donkey Kong Country: Tropical Freeze v1.0.1', image: './covers/Donkey Kong Country: Tropical Freeze v1.0.1.png' },
  { name: 'Doom', image: './covers/Doom.png' },
  { name: 'Doom 64 v1.0.2', image: './covers/Doom 64 v1.0.2.png' },
  { name: 'Dora Chie: Mini-Dora Ongakutai to 7-tsu no Chie (Brain Training) v1.1.0', image: './covers/Dora Chie: Mini-Dora Ongakutai to 7-tsu no Chie (Brain Training) v1.1.0.png' },
  { name: 'Dora Eigo: Nobita to Yousei no Fushigi Collection (English Training) v1.1.0', image: './covers/Dora Eigo: Nobita to Yousei no Fushigi Collection (English Training) v1.1.0.png' },
  { name: 'Dora Kazu: Nobita no Suuji Daibouken (Math Training) v1.1.0', image: './covers/Dora Kazu: Nobita no Suuji Daibouken (Math Training) v1.1.0.png' },
  { name: 'Dora Moji: Nobita no Kanji Daibouken (Hiragana, Katakana, and Kanji Training) v1.1.0', image: './covers/Dora Moji: Nobita no Kanji Daibouken (Hiragana, Katakana, and Kanji Training) v1.1.0.png' },
  { name: 'Doraemon Nobita no Bokujo Monogatari', image: './covers/Doraemon Nobita no Bokujo Monogatari.png' },
  { name: 'Doraemon Nobita\'s Brain Exercise Adventure', image: './covers/Doraemon Nobita\'s Brain Exercise Adventure.png' },
  { name: 'Doraemon Story of Seasons: Friends of the Great Kingdom', image: './covers/Doraemon Story of Seasons: Friends of the Great Kingdom.png' },
  { name: 'Double Dragon Gaiden: Rise of the Dragons v1.0.2', image: './covers/Double Dragon Gaiden: Rise of the Dragons v1.0.2.png' },
  { name: 'Dr Kawashima\'s Brain Training', image: './covers/Dr Kawashima\'s Brain Training.png' },
  { name: 'Dragon Quest Builders', image: './covers/Dragon Quest Builders.png' },
  { name: 'Dragon Quest Builders 2', image: './covers/Dragon Quest Builders 2.png' },
  { name: 'Dragon Quest Monsters: The Dark Prince v1.0.1', image: './covers/Dragon Quest Monsters: The Dark Prince v1.0.1.png' },
  { name: 'Dragon Quest Treasures', image: './covers/Dragon Quest Treasures.png' },
  { name: 'Dragon Quest III HD-2D Remake v1.0.1', image: './covers/Dragon Quest III HD-2D Remake v1.0.1.png' },
  { name: 'Dragon Quest XI S: Echoes of an Elusive Age – Definitive Edition', image: './covers/Dragon Quest XI S: Echoes of an Elusive Age – Definitive Edition.png' },
  { name: 'Dragon\'s Dogma: Dark Arisen', image: './covers/Dragon\'s Dogma: Dark Arisen.png' },
  { name: 'Dragon Ball FighterZ', image: './covers/Dragon Ball FighterZ.png' },
  { name: 'Dragon Ball Z: Kakarot + A New Power Awakens Set', image: './covers/Dragon Ball Z: Kakarot + A New Power Awakens Set.png' },
  { name: 'Dredge v1.0.1', image: './covers/Dredge v1.0.1.png' },
  { name: 'Dungeon of the Endless', image: './covers/Dungeon of the Endless.png' },
  { name: 'Dusk Diver 2', image: './covers/Dusk Diver 2.png' },
  { name: 'Dying Light: Platinum Edition', image: './covers/Dying Light: Platinum Edition.png' },
  { name: 'EA Sports FC 24', image: './covers/EA Sports FC 24.png' },
  { name: 'EA Sports FC 25', image: './covers/EA Sports FC 25.png' },
  { name: 'Eiyuden Chronicle: Hundred Heroes v1.01', image: './covers/Eiyuden Chronicle: Hundred Heroes v1.01.png' },
  { name: 'El Shaddai: Ascension of the Metatron HD Remaster', image: './covers/El Shaddai: Ascension of the Metatron HD Remaster.png' },
  { name: 'Emio – The Smiling Man: Famicom Detective Club', image: './covers/Emio – The Smiling Man: Famicom Detective Club.png' },
  { name: 'Ender Lilies: Quietus of the Knights v1.1.5b', image: './covers/Ender Lilies: Quietus of the Knights v1.1.5b.png' },
  { name: 'Endless Ocean Luminous', image: './covers/Endless Ocean Luminous.png' },
  { name: 'Etrian Odyssey HD Remaster', image: './covers/Etrian Odyssey HD Remaster.png' },
  { name: 'Etrian Odyssey II HD Remaster', image: './covers/Etrian Odyssey II HD Remaster.png' },
  { name: 'Etrian Odyssey III HD Remaster', image: './covers/Etrian Odyssey III HD Remaster.png' },
  { name: 'Fairy Tail', image: './covers/Fairy Tail.png' },
  { name: 'Fantasy Friends', image: './covers/Fantasy Friends.png' },
  { name: 'Fashion Dreamer', image: './covers/Fashion Dreamer.png' },
  { name: 'Fatal Frame: Maiden of Black Water (Project Zero: Maiden of Black Water)', image: './covers/Fatal Frame: Maiden of Black Water (Project Zero: Maiden of Black Water).png' },
  { name: 'Fatal Frame: Mask of the Lunar Eclipse', image: './covers/Fatal Frame: Mask of the Lunar Eclipse.png' },
  { name: 'Fate/Extella Link', image: './covers/Fate/Extella Link.png' },
  { name: 'Fate/Extella: The Umbral Star', image: './covers/Fate/Extella: The Umbral Star.png' },
  { name: 'Fate/Samurai Remnant (Fate/stay night Remastered)', image: './covers/Fate/Samurai Remnant (Fate/stay night Remastered).png' },
  { name: 'FIFA 21 Legacy Edition', image: './covers/FIFA 21 Legacy Edition.png' },
  { name: 'FIFA 22 Legacy Edition', image: './covers/FIFA 22 Legacy Edition.png' },
  { name: 'FIFA 23 Legacy Edition', image: './covers/FIFA 23 Legacy Edition.png' },
  { name: 'Final Fantasy VII v1.0.2_5', image: './covers/Final Fantasy VII v1.0.2_5.png' },
  { name: 'Final Fantasy VIII Remastered v1.0.1_5', image: './covers/Final Fantasy VIII Remastered v1.0.1_5.png' },
  { name: 'Final Fantasy X/X-2 HD Remaster', image: './covers/Final Fantasy X/X-2 HD Remaster.png' },
  { name: 'Final Fantasy XII: The Zodiac Age', image: './covers/Final Fantasy XII: The Zodiac Age.png' },
  { name: 'Fire Emblem Engage', image: './covers/Fire Emblem Engage.png' },
  { name: 'Fire Emblem: Three Houses', image: './covers/Fire Emblem: Three Houses.png' },
  { name: 'Fire Emblem Warriors', image: './covers/Fire Emblem Warriors.png' },
  { name: 'Fire Emblem Warriors: Three Hopes v1.0.1', image: './covers/Fire Emblem Warriors: Three Hopes v1.0.1.png' },
  { name: 'Fishing Star World Tour', image: './covers/Fishing Star World Tour.png' },
  { name: 'F.I.S.T.: Forged In Shadow Torch', image: './covers/F.I.S.T.: Forged In Shadow Torch.png' },
  { name: 'Fitness Boxing', image: './covers/Fitness Boxing.png' },
  { name: 'Fitness Boxing feat. Hatsune Miku', image: './covers/Fitness Boxing feat. Hatsune Miku.png' },
  { name: 'Fitness Boxing: Fist of the North Star', image: './covers/Fitness Boxing: Fist of the North Star.png' },
  { name: 'Fitness Boxing 2: Rhythm & Exercise', image: './covers/Fitness Boxing 2: Rhythm & Exercise.png' },
  { name: 'Five Nights at Freddy\'s v1.0.1', image: './covers/Five Nights at Freddy\'s v1.0.1.png' },
  { name: 'Five Nights at Freddy\'s 2 v1.0.3', image: './covers/Five Nights at Freddy\'s 2 v1.0.3.png' },
  { name: 'Five Nights at Freddy\'s 3 v1.0.1', image: './covers/Five Nights at Freddy\'s 3 v1.0.1.png' },
  { name: 'Five Nights at Freddy\'s 4 v1.0.2', image: './covers/Five Nights at Freddy\'s 4 v1.0.2.png' },
  { name: 'Five Nights at Freddy\'s: Sister Location v1.0.1', image: './covers/Five Nights at Freddy\'s: Sister Location v1.0.1.png' },
  { name: 'Five Nights at Freddy\'s: Security Breach v0.3', image: './covers/Five Nights at Freddy\'s: Security Breach v0.3.png' },
  { name: 'Game Builder Garage', image: './covers/Game Builder Garage.png' },
  { name: 'Gensoukissa Enchante', image: './covers/Gensoukissa Enchante.png' },
  { name: 'GetsuFumaDen v1.0.1', image: './covers/GetsuFumaDen v1.0.1.png' },
  { name: 'GetsuFumaDen: Undying Moon + DLC v1.1.1', image: './covers/GetsuFumaDen: Undying Moon + DLC v1.1.1.png' },
  { name: 'Ghost Trick: Phantom Detective', image: './covers/Ghost Trick: Phantom Detective.png' },
  { name: 'Ghostrunner', image: './covers/Ghostrunner.png' },
  { name: 'Giana Sisters: Twisted Dreams – Owltimate Edition', image: './covers/Giana Sisters: Twisted Dreams – Owltimate Edition.png' },
  { name: 'Goat Simulator 3 v1.0.7.1', image: './covers/Goat Simulator 3 v1.0.7.1.png' },
  { name: 'God Eater 3', image: './covers/God Eater 3.png' },
  { name: 'Grand Theft Auto III – The Definitive Edition v1.0.4', image: './covers/Grand Theft Auto III – The Definitive Edition v1.0.4.png' },
  { name: 'Grand Theft Auto: Vice City – The Definitive Edition v1.0.1', image: './covers/Grand Theft Auto: Vice City – The Definitive Edition v1.0.1.png' },
  { name: 'Grand Theft Auto: San Andreas – The Definitive Edition v1.0.4', image: './covers/Grand Theft Auto: San Andreas – The Definitive Edition v1.0.4.png' },
  { name: 'Greak: Memories of Azur', image: './covers/Greak: Memories of Azur.png' },
  { name: 'Grip: Combat Racing', image: './covers/Grip: Combat Racing.png' },
  { name: 'Guacamelee! Super Turbo Championship Edition', image: './covers/Guacamelee! Super Turbo Championship Edition.png' },
  { name: 'Guacamelee! 2 v1.0.3', image: './covers/Guacamelee! 2 v1.0.3.png' },
  { name: 'Guilty Gear', image: './covers/Guilty Gear.png' },
  { name: 'Guilty Gear XX Accent Core Plus R v1.0.1', image: './covers/Guilty Gear XX Accent Core Plus R v1.0.1.png' },
  { name: 'Gundam Breaker 4 v1.1.0', image: './covers/Gundam Breaker 4 v1.1.0.png' },
  { name: 'Hades v1.0.37136', image: './covers/Hades v1.0.37136.png' },
  { name: 'Hard West Ultimate Edition', image: './covers/Hard West Ultimate Edition.png' },
  { name: 'Hardcore Mecha + 6 DLC', image: './covers/Hardcore Mecha + 6 DLC.png' },
  { name: 'Harvest Moon: The Winds of Anthos', image: './covers/Harvest Moon: The Winds of Anthos.png' },
  { name: 'Harvestella', image: './covers/Harvestella.png' },
  { name: 'Hatsune Miku: Project Diva Mega Mix (Hatsune Miku: Project Diva Mega39\'s)', image: './covers/Hatsune Miku: Project Diva Mega Mix (Hatsune Miku: Project Diva Mega39\'s).png' },
  { name: 'Hoa v1.0.4', image: './covers/Hoa v1.0.4.png' },
  { name: 'Hogwarts Legacy', image: './covers/Hogwarts Legacy.png' },
  { name: 'Hollow Knight v1.4.3.2', image: './covers/Hollow Knight v1.4.3.2.png' },
  { name: 'Hot Wheels Unleashed', image: './covers/Hot Wheels Unleashed.png' },
  { name: 'Human: Fall Flat v1.4.8', image: './covers/Human: Fall Flat v1.4.8.png' },
  { name: 'Hyrule Warriors: Age of Calamity v1.3.0', image: './covers/Hyrule Warriors: Age of Calamity v1.3.0.png' },
  { name: 'Hyrule Warriors: Definitive Edition', image: './covers/Hyrule Warriors: Definitive Edition.png' },
  { name: 'I am Setsuna', image: './covers/I am Setsuna.png' },
  { name: 'Immortals Fenyx Rising', image: './covers/Immortals Fenyx Rising.png' },
  { name: 'Infinity Strash: Dragon Quest The Adventure of Dai', image: './covers/Infinity Strash: Dragon Quest The Adventure of Dai.png' },
  { name: 'Into the Breach v1.2.75', image: './covers/Into the Breach v1.2.75.png' },
  { name: 'It Takes Two + 2 DLC', image: './covers/It Takes Two + 2 DLC.png' },
  { name: 'Jack Jeanne', image: './covers/Jack Jeanne.png' },
  { name: 'Jump Force Deluxe Edition v1.02', image: './covers/Jump Force Deluxe Edition v1.02.png' },
  { name: 'Just Dance 2018', image: './covers/Just Dance 2018.png' },
  { name: 'Just Dance 2019 v290003.438003', image: './covers/Just Dance 2019 v290003.438003.png' },
  { name: 'Just Dance 2020', image: './covers/Just Dance 2020.png' },
  { name: 'Just Dance 2021', image: './covers/Just Dance 2021.png' },
  { name: 'Just Dance 2022', image: './covers/Just Dance 2022.png' },
  { name: 'Kage: Shadow of The Ninja (Shadow of the Ninja – Reborn)', image: './covers/Kage: Shadow of The Ninja (Shadow of the Ninja – Reborn).png' },
  { name: 'Kao the Kangaroo', image: './covers/Kao the Kangaroo.png' },
  { name: 'Katana Kami: A Way of the Samurai Story', image: './covers/Katana Kami: A Way of the Samurai Story.png' },
  { name: 'KeyWe', image: './covers/KeyWe.png' },
  { name: 'Kingdom Come Deliverance: Royal Edition', image: './covers/Kingdom Come Deliverance: Royal Edition.png' },
  { name: 'Kingdom Hearts: Melody of Memory v1.01', image: './covers/Kingdom Hearts: Melody of Memory v1.01.png' },
  { name: 'Kingdom: New Lands v1.3.1b', image: './covers/Kingdom: New Lands v1.3.1b.png' },
  { name: 'Kingdom Two Crowns v1.08b', image: './covers/Kingdom Two Crowns v1.08b.png' },
  { name: 'Kingdoms of Amalur: Re-Reckoning', image: './covers/Kingdoms of Amalur: Re-Reckoning.png' },
  { name: 'Kirby and the Forgotten Land', image: './covers/Kirby and the Forgotten Land.png' },
  { name: 'Kirby Star Allies v3.0.0', image: './covers/Kirby Star Allies v3.0.0.png' },
  { name: 'Kirby\'s Return to Dream Land Deluxe', image: './covers/Kirby\'s Return to Dream Land Deluxe.png' },
  { name: 'Kitaria Fables', image: './covers/Kitaria Fables.png' },
  { name: 'Klonoa Phantasy Reverie Series', image: './covers/Klonoa Phantasy Reverie Series.png' },
  { name: 'Layers of Fear: Legacy v1.0.1', image: './covers/Layers of Fear: Legacy v1.0.1.png' },
  { name: 'Layton\'s Mystery Journey: Katrielle and the Millionaires\' Conspiracy Deluxe Edition', image: './covers/Layton\'s Mystery Journey: Katrielle and the Millionaires\' Conspiracy Deluxe Edition.png' },
  { name: 'Legend of Kay Anniversary', image: './covers/Legend of Kay Anniversary.png' },
  { name: 'LEGO City Undercover', image: './covers/LEGO City Undercover.png' },
  { name: 'LEGO DC Super-Villains', image: './covers/LEGO DC Super-Villains.png' },
  { name: 'LEGO Harry Potter Collection', image: './covers/LEGO Harry Potter Collection.png' },
  { name: 'LEGO Horizon Adventures', image: './covers/LEGO Horizon Adventures.png' },
  { name: 'LEGO Jurassic World', image: './covers/LEGO Jurassic World.png' },
  { name: 'LEGO Marvel Super Heroes', image: './covers/LEGO Marvel Super Heroes.png' },
  { name: 'LEGO Marvel Super Heroes 2', image: './covers/LEGO Marvel Super Heroes 2.png' },
  { name: 'LEGO Movie 2 Videogame, The', image: './covers/LEGO Movie 2 Videogame, The.png' },
  { name: 'LEGO Ninjago Movie Videogame, The', image: './covers/LEGO Ninjago Movie Videogame, The.png' },
  { name: 'LEGO Star Wars: The Skywalker Saga', image: './covers/LEGO Star Wars: The Skywalker Saga.png' },
  { name: 'LEGO The Incredibles', image: './covers/LEGO The Incredibles.png' },
  { name: 'LEGO Worlds', image: './covers/LEGO Worlds.png' },
  { name: 'LEGO 2K Drive v1.2', image: './covers/LEGO 2K Drive v1.2.png' },
  { name: 'Let\'s Get Fit', image: './covers/Let\'s Get Fit.png' },
  { name: 'Let\'s Sing 2024', image: './covers/Let\'s Sing 2024.png' },
  { name: 'Little Friends: Dogs & Cats', image: './covers/Little Friends: Dogs & Cats.png' },
  { name: 'Little Nightmares Complete Edition v1.0.2', image: './covers/Little Nightmares Complete Edition v1.0.2.png' },
  { name: 'Little Nightmares II', image: './covers/Little Nightmares II.png' },
  { name: 'Live A Live', image: './covers/Live A Live.png' },
  { name: 'L.O.L. Surprise! Movie Night', image: './covers/L.O.L. Surprise! Movie Night.png' },
  { name: 'Loop8: Summer of Gods', image: './covers/Loop8: Summer of Gods.png' },
  { name: 'Lost Sphear v1.1.0', image: './covers/Lost Sphear v1.1.0.png' },
  { name: 'LoveKami -Divinity Stage- v1.0.1', image: './covers/LoveKami -Divinity Stage- v1.0.1.png' },
  { name: 'LoveKami -Useless Goddess- v1.1.0', image: './covers/LoveKami -Useless Goddess- v1.1.0.png' },
  { name: 'LoveKami -Healing Harem- v1.0.1', image: './covers/LoveKami -Healing Harem- v1.0.1.png' },
  { name: 'Lovers in a Dangerous Spacetime v1.0.4', image: './covers/Lovers in a Dangerous Spacetime v1.0.4.png' },
  { name: 'Luigi\'s Mansion 2 HD', image: './covers/Luigi\'s Mansion 2 HD.png' },
  { name: 'Luigi\'s Mansion 3 v1.2.1', image: './covers/Luigi\'s Mansion 3 v1.2.1.png' },
  { name: 'Maid of the Dead', image: './covers/Maid of the Dead.png' },
  { name: 'Maneater', image: './covers/Maneater.png' },
  { name: 'Mario & Luigi: Brothership', image: './covers/Mario & Luigi: Brothership.png' },
  { name: 'Mario & Sonic at the Olympic Games Tokyo 2020', image: './covers/Mario & Sonic at the Olympic Games Tokyo 2020.png' },
  { name: 'Mario Golf: Super Rush', image: './covers/Mario Golf: Super Rush.png' },
  { name: 'Mario Kart 8 Deluxe + DLC v2.4.0', image: './covers/Mario Kart 8 Deluxe + DLC v2.4.0.png' },
  { name: 'Mario Party Superstars v1.1.1', image: './covers/Mario Party Superstars v1.1.1.png' },
  { name: 'Mario + Rabbids Kingdom Battle', image: './covers/Mario + Rabbids Kingdom Battle.png' },
  { name: 'Mario + Rabbids Sparks of Hope', image: './covers/Mario + Rabbids Sparks of Hope.png' },
  { name: 'Mario Strikers: Battle League', image: './covers/Mario Strikers: Battle League.png' },
  { name: 'Mario Tennis Aces v3.1.0', image: './covers/Mario Tennis Aces v3.1.0.png' },
  { name: 'Mario vs. Donkey Kong', image: './covers/Mario vs. Donkey Kong.png' },
  { name: 'Marsupilami: Hoobadventure', image: './covers/Marsupilami: Hoobadventure.png' },
  { name: 'Marvel Ultimate Alliance 3: The Black Order', image: './covers/Marvel Ultimate Alliance 3: The Black Order.png' },
  { name: 'Master Detective Archives: Rain Code', image: './covers/Master Detective Archives: Rain Code.png' },
  { name: 'Mega Man 11', image: './covers/Mega Man 11.png' },
  { name: 'Mega Man Battle Network Legacy Collection Vol.1', image: './covers/Mega Man Battle Network Legacy Collection Vol.1.png' },
  { name: 'Mega Man Battle Network Legacy Collection Vol.2', image: './covers/Mega Man Battle Network Legacy Collection Vol.2.png' },
  { name: 'Mega Man Zero/ZX Legacy Collection', image: './covers/Mega Man Zero/ZX Legacy Collection.png' },
  { name: 'Megadimension Neptunia VII', image: './covers/Megadimension Neptunia VII.png' },
  { name: 'Meido in Abusu: Yami o Mezashita Rensei', image: './covers/Meido in Abusu: Yami o Mezashita Rensei.png' },
  { name: 'Memories Off 1 v1.0.1', image: './covers/Memories Off 1 v1.0.1.png' },
  { name: 'Memories Off 2 v1.0.1', image: './covers/Memories Off 2 v1.0.1.png' },
  { name: 'Memories Off 3: Omoide ni Kawaru Kimi v1.0.1', image: './covers/Memories Off 3: Omoide ni Kawaru Kimi v1.0.1.png' },
  { name: 'Memories Off: Sorekara v1.0.1', image: './covers/Memories Off: Sorekara v1.0.1.png' },
  { name: 'Memories Off 5: Togireta Film', image: './covers/Memories Off 5: Togireta Film.png' },
  { name: 'Memories Off 6: T-wave', image: './covers/Memories Off 6: T-wave.png' },
  { name: 'Memories Off: Yubikiri no Kioku', image: './covers/Memories Off: Yubikiri no Kioku.png' },
  { name: 'Memories Off -Innocent Fille-', image: './covers/Memories Off -Innocent Fille-.png' },
  { name: 'Memories Off -Innocent Fille- for Dearest', image: './covers/Memories Off -Innocent Fille- for Dearest.png' },
  { name: 'Metal Gear Solid – Master Collection Version v1.1.1', image: './covers/Metal Gear Solid – Master Collection Version v1.1.1.png' },
  { name: 'Metal Gear Solid 2: Sons of Liberty – Master Collection Version v1.1.1', image: './covers/Metal Gear Solid 2: Sons of Liberty – Master Collection Version v1.1.1.png' },
  { name: 'Metal Gear Solid 3: Snake Eater – Master Collection Version v1.1.2', image: './covers/Metal Gear Solid 3: Snake Eater – Master Collection Version v1.1.2.png' },
  { name: 'Metal Gear & Metal Gear 2: Solid Snake v1.1.2', image: './covers/Metal Gear & Metal Gear 2: Solid Snake v1.1.2.png' },
  { name: 'Metal Gear Solid: Master Collection Vol. 1 Bonus Content v1.1.2', image: './covers/Metal Gear Solid: Master Collection Vol. 1 Bonus Content v1.1.2.png' },
  { name: 'Metroid Dread', image: './covers/Metroid Dread.png' },
  { name: 'Metroid Prime Remastered', image: './covers/Metroid Prime Remastered.png' },
  { name: 'Miitopia v1.0.3', image: './covers/Miitopia v1.0.3.png' },
  { name: 'Minecraft v1.2.12.0', image: './covers/Minecraft v1.2.12.0.png' },
  { name: 'Minecraft Dungeons + 7 DLC v1.10.4.0', image: './covers/Minecraft Dungeons + 7 DLC v1.10.4.0.png' },
  { name: 'MLB The Show 23', image: './covers/MLB The Show 23.png' },
  { name: 'MLB The Show 24', image: './covers/MLB The Show 24.png' },
  { name: 'Moero Crystal H', image: './covers/Moero Crystal H.png' },
  { name: 'Monopoly v1.0.5', image: './covers/Monopoly v1.0.5.png' },
  { name: 'Monopoly Madness', image: './covers/Monopoly Madness.png' },
  { name: 'Monster Boy and the Cursed Kingdom v1.0.1', image: './covers/Monster Boy and the Cursed Kingdom v1.0.1.png' },
  { name: 'Monster Hunter Generations Ultimate', image: './covers/Monster Hunter Generations Ultimate.png' },
  { name: 'Monster Hunter: Rise', image: './covers/Monster Hunter: Rise.png' },
  { name: 'Monster Hunter Stories 2: Wings of Ruin v1.0.1', image: './covers/Monster Hunter Stories 2: Wings of Ruin v1.0.1.png' },
  { name: 'Monster Hunter XX: Double Cross', image: './covers/Monster Hunter XX: Double Cross.png' },
  { name: 'Moonlighter v1.0.0.1', image: './covers/Moonlighter v1.0.0.1.png' },
  { name: 'Mortal Kombat 11', image: './covers/Mortal Kombat 11.png' },
  { name: 'Moving Out 2', image: './covers/Moving Out 2.png' },
  { name: 'Mutant Football League: Dynasty Edition', image: './covers/Mutant Football League: Dynasty Edition.png' },
  { name: 'My Friend Peppa Pig', image: './covers/My Friend Peppa Pig.png' },
  { name: 'My Girlfriend is a Mermaid!?', image: './covers/My Girlfriend is a Mermaid!?.png' },
  { name: 'My Hero One\'s Justice', image: './covers/My Hero One\'s Justice.png' },
  { name: 'My Hero One\'s Justice 2', image: './covers/My Hero One\'s Justice 2.png' },
  { name: 'My Little Pony: A Maretime Bay Adventure', image: './covers/My Little Pony: A Maretime Bay Adventure.png' },
  { name: 'My Little Pony: A Zephyr Heights Mystery', image: './covers/My Little Pony: A Zephyr Heights Mystery.png' },
  { name: 'My Next Life as a Villainess: All Routes Lead to Doom! -Pirates of the Disturbance-', image: './covers/My Next Life as a Villainess: All Routes Lead to Doom! -Pirates of the Disturbance-.png' },
  { name: 'Naruto Shippuden: Ultimate Ninja Storm 4 – Road to Boruto', image: './covers/Naruto Shippuden: Ultimate Ninja Storm 4 – Road to Boruto.png' },
  { name: 'Naruto X Boruto: Ultimate Ninja Storm Connections', image: './covers/Naruto X Boruto: Ultimate Ninja Storm Connections.png' },
  { name: 'Natsu-Mon: 20th Century Summer Kid', image: './covers/Natsu-Mon: 20th Century Summer Kid.png' },
  { name: 'Nayuta no Kiseki: Ad Astra (The Legend of Nayuta: Boundless Trails)', image: './covers/Nayuta no Kiseki: Ad Astra (The Legend of Nayuta: Boundless Trails).png' },
  { name: 'NBA 2K Playgrounds 2', image: './covers/NBA 2K Playgrounds 2.png' },
  { name: 'NBA 2K21', image: './covers/NBA 2K21.png' },
  { name: 'NBA 2K23', image: './covers/NBA 2K23.png' },
  { name: 'NBA 2K24 Kobe Bryant Edition', image: './covers/NBA 2K24 Kobe Bryant Edition.png' },
  { name: 'NBA 2K25', image: './covers/NBA 2K25.png' },
  { name: 'Need for Speed: Hot Pursuit Remastered', image: './covers/Need for Speed: Hot Pursuit Remastered.png' },
  { name: 'Nerf Legends', image: './covers/Nerf Legends.png' },
  { name: 'New Pokémon Snap', image: './covers/New Pokémon Snap.png' },
  { name: 'New Super Lucky\'s Tale', image: './covers/New Super Lucky\'s Tale.png' },
  { name: 'New Super Mario Bros. U Deluxe', image: './covers/New Super Mario Bros. U Deluxe.png' },
  { name: 'Nickelodeon Kart Racers 3: Slime Speedway', image: './covers/Nickelodeon Kart Racers 3: Slime Speedway.png' },
  { name: 'NieR: Automata The End of YoRHa Edition v1.0.2', image: './covers/NieR: Automata The End of YoRHa Edition v1.0.2.png' },
  { name: 'Ninja Gaiden Sigma', image: './covers/Ninja Gaiden Sigma.png' },
  { name: 'Ninja Gaiden Sigma 2', image: './covers/Ninja Gaiden Sigma 2.png' },
  { name: 'Ninja Gaiden 3: Razor\'s Edge', image: './covers/Ninja Gaiden 3: Razor\'s Edge.png' },
  { name: 'Nintendo Switch Sports v1.4.0', image: './covers/Nintendo Switch Sports v1.4.0.png' },
  { name: 'No Man\'s Sky', image: './covers/No Man\'s Sky.png' },
  { name: 'No More Heroes', image: './covers/No More Heroes.png' },
  { name: 'No More Heroes 2: Desperate Struggle', image: './covers/No More Heroes 2: Desperate Struggle.png' },
  { name: 'Octopath Traveler v1.0.3', image: './covers/Octopath Traveler v1.0.3.png' },
  { name: 'Octopath Traveler II', image: './covers/Octopath Traveler II.png' },
  { name: 'Olympia Soiree', image: './covers/Olympia Soiree.png' },
  { name: 'Omori', image: './covers/Omori.png' },
  { name: 'One Piece: Pirate Warriors 4', image: './covers/One Piece: Pirate Warriors 4.png' },
  { name: 'One Piece: Unlimited World Red Deluxe Edition', image: './covers/One Piece: Unlimited World Red Deluxe Edition.png' },
  { name: 'Onimusha: Warlords', image: './covers/Onimusha: Warlords.png' },
  { name: 'Oninaki', image: './covers/Oninaki.png' },
  { name: 'Ori and the Blind Forest: Definitive Edition v1.0.2', image: './covers/Ori and the Blind Forest: Definitive Edition v1.0.2.png' },
  { name: 'Ori and the Will of the Wisps v1.2.0', image: './covers/Ori and the Will of the Wisps v1.2.0.png' },
  { name: 'Overcooked! 2 v1.0.4', image: './covers/Overcooked! 2 v1.0.4.png' },
  { name: 'Overcooked! All You Can Eat v1.0.1', image: './covers/Overcooked! All You Can Eat v1.0.1.png' },
  { name: 'Override 2: Super Mech League', image: './covers/Override 2: Super Mech League.png' },
  { name: 'Paper Mario: The Origami King', image: './covers/Paper Mario: The Origami King.png' },
  { name: 'Paper Mario: The Thousand-Year Door', image: './covers/Paper Mario: The Thousand-Year Door.png' },
  { name: 'PAW Patrol: Grand Prix v1.0.1', image: './covers/PAW Patrol: Grand Prix v1.0.1.png' },
  { name: 'PAW Patrol: Mighty Pups Save Adventure Bay!', image: './covers/PAW Patrol: Mighty Pups Save Adventure Bay!.png' },
  { name: 'PAW Patrol: On a Roll!', image: './covers/PAW Patrol: On a Roll!.png' },
  { name: 'PAW Patrol The Movie: Adventure City Calls v1.3.0', image: './covers/PAW Patrol The Movie: Adventure City Calls v1.3.0.png' },
  { name: 'PAW Patrol World', image: './covers/PAW Patrol World.png' },
  { name: 'Persona 4 Golden v1.0.2', image: './covers/Persona 4 Golden v1.0.2.png' },
  { name: 'Persona 5 Royal', image: './covers/Persona 5 Royal.png' },
  { name: 'Persona 5 Strikers', image: './covers/Persona 5 Strikers.png' },
  { name: 'Persona 5 Tactica', image: './covers/Persona 5 Tactica.png' },
  { name: 'Phoenix Wright: Ace Attorney Trilogy', image: './covers/Phoenix Wright: Ace Attorney Trilogy.png' },
  { name: 'Pikmin 1 + Pikmin 2', image: './covers/Pikmin 1 + Pikmin 2.png' },
  { name: 'Pikmin 3 Deluxe', image: './covers/Pikmin 3 Deluxe.png' },
  { name: 'Pikmin 4 v1.0.1', image: './covers/Pikmin 4 v1.0.1.png' },
  { name: 'Piofiore no Banshou -ricordo-', image: './covers/Piofiore no Banshou -ricordo-.png' },
  { name: 'Plants vs. Zombies: Battle for Neighborville Complete Edition', image: './covers/Plants vs. Zombies: Battle for Neighborville Complete Edition.png' },
  { name: 'Pokémon Brilliant Diamond v1.1.2', image: './covers/Pokémon Brilliant Diamond v1.1.2.png' },
  { name: 'Pokémon Legends: Arceus v1.0.1', image: './covers/Pokémon Legends: Arceus v1.0.1.png' },
  { name: 'Pokémon: Let\'s Go, Eevee!', image: './covers/Pokémon: Let\'s Go, Eevee!.png' },
  { name: 'Pokémon: Let\'s Go, Pikachu!', image: './covers/Pokémon: Let\'s Go, Pikachu!.png' },
  { name: 'Pokémon Mystery Dungeon: Rescue Team DX v1.0.1', image: './covers/Pokémon Mystery Dungeon: Rescue Team DX v1.0.1.png' },
  { name: 'Pokémon Scarlet + 2 DLC v3.0.0', image: './covers/Pokémon Scarlet + 2 DLC v3.0.0.png' },
  { name: 'Pokémon Shield + 2 DLC v1.3.0', image: './covers/Pokémon Shield + 2 DLC v1.3.0.png' },
  { name: 'Pokémon Shining Pearl', image: './covers/Pokémon Shining Pearl.png' },
  { name: 'Pokémon Sword + 2 DLC v1.3.0', image: './covers/Pokémon Sword + 2 DLC v1.3.0.png' },
  { name: 'Pokémon Violet + 2 DLC v2.0.1', image: './covers/Pokémon Violet + 2 DLC v2.0.1.png' },
  { name: 'Pokkén Tournament DX', image: './covers/Pokkén Tournament DX.png' },
  { name: 'Potion Permit', image: './covers/Potion Permit.png' },
  { name: 'Potionomics: Masterwork Edition', image: './covers/Potionomics: Masterwork Edition.png' },
  { name: 'Prince of Persia: The Lost Crown', image: './covers/Prince of Persia: The Lost Crown.png' },
  { name: 'Princess Peach: Showtime!', image: './covers/Princess Peach: Showtime!.png' },
  { name: 'Prinny: Can I Really Be the Hero? v1.0.1', image: './covers/Prinny: Can I Really Be the Hero? v1.0.1.png' },
  { name: 'Prinny 2: Dawn of Operation Panties, Dood!', image: './covers/Prinny 2: Dawn of Operation Panties, Dood!.png' },
  { name: 'Puyo Puyo Tetris 2', image: './covers/Puyo Puyo Tetris 2.png' },
  { name: 'Puzzle Bobble Everybubble!', image: './covers/Puzzle Bobble Everybubble!.png' },
  { name: 'Rabbids: Party of Legends v1.0.1', image: './covers/Rabbids: Party of Legends v1.0.1.png' },
  { name: 'Rain on Your Parade + DLC v1.2.8', image: './covers/Rain on Your Parade + DLC v1.2.8.png' },
  { name: 'Rayman Legends Definitive Edition', image: './covers/Rayman Legends Definitive Edition.png' },
  { name: 'Re:Zero -Starting Life in Another World- The Prophecy of the Throne', image: './covers/Re:Zero -Starting Life in Another World- The Prophecy of the Throne.png' },
  { name: 'Red Dead Redemption', image: './covers/Red Dead Redemption.png' },
  { name: 'Resident Evil 0', image: './covers/Resident Evil 0.png' },
  { name: 'Resident Evil 4', image: './covers/Resident Evil 4.png' },
  { name: 'Resident Evil: Revelations', image: './covers/Resident Evil: Revelations.png' },
  { name: 'Ring Fit Adventure v1.2.0', image: './covers/Ring Fit Adventure v1.2.0.png' },
  { name: 'Risk of Rain v1.0.3', image: './covers/Risk of Rain v1.0.3.png' },
  { name: 'Risk of Rain 2 v1.0.1', image: './covers/Risk of Rain 2 v1.0.1.png' },
  { name: 'River City Saga: Three Kingdoms', image: './covers/River City Saga: Three Kingdoms.png' },
  { name: 'Road 96 v1.01', image: './covers/Road 96 v1.01.png' },
  { name: 'Rockman X Anniversary Collection', image: './covers/Rockman X Anniversary Collection.png' },
  { name: 'Romancing SaGa 2: Revenge of the Seven', image: './covers/Romancing SaGa 2: Revenge of the Seven.png' },
  { name: 'Romancing SaGa 3', image: './covers/Romancing SaGa 3.png' },
  { name: 'Root Letter: Last Answer', image: './covers/Root Letter: Last Answer.png' },
  { name: 'RPG Maker With', image: './covers/RPG Maker With.png' },
  { name: 'Rune Factory 3 Special', image: './covers/Rune Factory 3 Special.png' },
  { name: 'Rune Factory 5', image: './covers/Rune Factory 5.png' },
  { name: 'Sakuna: Of Rice and Ruin', image: './covers/Sakuna: Of Rice and Ruin.png' },
  { name: 'Salt and Sanctuary v1.0.1', image: './covers/Salt and Sanctuary v1.0.1.png' },
  { name: 'Samurai Jack: Battle Through Time v1.0.4', image: './covers/Samurai Jack: Battle Through Time v1.0.4.png' },
  { name: 'Samurai Shodown (Samurai Spirits)', image: './covers/Samurai Shodown (Samurai Spirits).png' },
  { name: 'Samurai Shodown NeoGeo Collection v1.0.1', image: './covers/Samurai Shodown NeoGeo Collection v1.0.1.png' },
  { name: 'Sangokushi 8 Remake (Romance of the Three Kingdoms 8 Remake)', image: './covers/Sangokushi 8 Remake (Romance of the Three Kingdoms 8 Remake).png' },
  { name: 'Sangokushi 13 with Power Up Kit + DLC (Romance of the Three Kingdoms XIII)', image: './covers/Sangokushi 13 with Power Up Kit + DLC (Romance of the Three Kingdoms XIII).png' },
  { name: 'Sangokushi 14 with Power Up Kit (Romance of the Three Kingdoms XIV)', image: './covers/Sangokushi 14 with Power Up Kit (Romance of the Three Kingdoms XIV).png' },
  { name: 'Sayonara Wild Hearts v1.2.0', image: './covers/Sayonara Wild Hearts v1.2.0.png' },
  { name: 'SD Gundam Battle Alliance', image: './covers/SD Gundam Battle Alliance.png' },
  { name: 'SD Gundam G Generation Cross Rays', image: './covers/SD Gundam G Generation Cross Rays.png' },
  { name: 'Sea of Stars v1.0.46981', image: './covers/Sea of Stars v1.0.46981.png' },
  { name: 'SeaBed', image: './covers/SeaBed.png' },
  { name: 'Serious Sam Collection v1.2.0', image: './covers/Serious Sam Collection v1.2.0.png' },
  { name: 'Shadowverse: Champion\'s Battle', image: './covers/Shadowverse: Champion\'s Battle.png' },
  { name: 'Shin-chan: Me and the Professor on Summer Vacation -The Endless Seven-Day Journey-', image: './covers/Shin-chan: Me and the Professor on Summer Vacation -The Endless Seven-Day Journey-.png' },
  { name: 'Shin-chan: Shiro and the Coal Town v1.0.1', image: './covers/Shin-chan: Shiro and the Coal Town v1.0.1.png' },
  { name: 'Shin Megami Tensei V: Vengeance', image: './covers/Shin Megami Tensei V: Vengeance.png' },
  { name: 'Shin Sangoku Musou 7 with Moushouden DX (Dynasty Warriors 8: Xtreme Legends)', image: './covers/Shin Sangoku Musou 7 with Moushouden DX (Dynasty Warriors 8: Xtreme Legends).png' },
  { name: 'Shin Sangoku Musou 8 Empires (Dynasty Warriors 9)', image: './covers/Shin Sangoku Musou 8 Empires (Dynasty Warriors 9).png' },
  { name: 'Shiren the Wanderer: The Mystery Dungeon of Serpentcoil Island', image: './covers/Shiren the Wanderer: The Mystery Dungeon of Serpentcoil Island.png' },
  { name: 'Shovel Knight: Treasure Trove v4.0A', image: './covers/Shovel Knight: Treasure Trove v4.0A.png' },
  { name: 'Sid Meier\'s Civilization VI', image: './covers/Sid Meier\'s Civilization VI.png' },
  { name: 'Sifu v1.11_790', image: './covers/Sifu v1.11_790.png' },
  { name: 'SINce Memories: Off the Starry Sky', image: './covers/SINce Memories: Off the Starry Sky.png' },
  { name: 'Skabma – Snowfall', image: './covers/Skabma – Snowfall.png' },
  { name: 'Skull Island: Rise of Kong', image: './covers/Skull Island: Rise of Kong.png' },
  { name: 'Slay the Spire', image: './covers/Slay the Spire.png' },
  { name: 'Snack World: The Dungeon Crawl – Gold', image: './covers/Snack World: The Dungeon Crawl – Gold.png' },
  { name: 'Sniper Elite 3 Ultimate Edition', image: './covers/Sniper Elite 3 Ultimate Edition.png' },
  { name: 'Sniper Elite 4', image: './covers/Sniper Elite 4.png' },
  { name: 'Snipperclips Plus: Cut It Out, Together! v1.1.0', image: './covers/Snipperclips Plus: Cut It Out, Together! v1.1.0.png' },
  { name: 'SNK Heroines Tag Team Frenzy', image: './covers/SNK Heroines Tag Team Frenzy.png' },
  { name: 'Snow Bros. Nick & Tom Special + DLC v1.0.2', image: './covers/Snow Bros. Nick & Tom Special + DLC v1.0.2.png' },
  { name: 'SnowRunner', image: './covers/SnowRunner.png' },
  { name: 'Some Some Convenience Store v1.0.4', image: './covers/Some Some Convenience Store v1.0.4.png' },
  { name: 'Sonic Forces', image: './covers/Sonic Forces.png' },
  { name: 'Sonic Frontiers', image: './covers/Sonic Frontiers.png' },
  { name: 'Sonic Mania v1.04', image: './covers/Sonic Mania v1.04.png' },
  { name: 'Team Sonic Racing', image: './covers/Team Sonic Racing.png' },
  { name: 'Sonic X Shadow Generations', image: './covers/Sonic X Shadow Generations.png' },
  { name: 'Space Invaders Forever', image: './covers/Space Invaders Forever.png' },
  { name: 'Arkanoid vs Space Invaders', image: './covers/Arkanoid vs Space Invaders.png' },
  { name: 'Spiritfarer v1.14', image: './covers/Spiritfarer v1.14.png' },
  { name: 'Splatoon 2', image: './covers/Splatoon 2.png' },
  { name: 'Splatoon 3', image: './covers/Splatoon 3.png' },
  { name: 'SpongeBob SquarePants: Battle for Bikini Bottom – Rehydrated', image: './covers/SpongeBob SquarePants: Battle for Bikini Bottom – Rehydrated.png' },
  { name: 'SpongeBob SquarePants: Krusty Cook-Off Extra Krusty Edition + 2 DLC v1.1.1', image: './covers/SpongeBob SquarePants: Krusty Cook-Off Extra Krusty Edition + 2 DLC v1.1.1.png' },
  { name: 'SpongeBob SquarePants: The Cosmic Shake', image: './covers/SpongeBob SquarePants: The Cosmic Shake.png' },
  { name: 'Sports Party', image: './covers/Sports Party.png' },
  { name: 'Spy x Family: Operation Diary (Spy x Anya: Operation Memories)', image: './covers/Spy x Family: Operation Diary (Spy x Anya: Operation Memories).png' },
  { name: 'Spyro Reignited Trilogy', image: './covers/Spyro Reignited Trilogy.png' },
  { name: 'Star Ocean: The Second Story R', image: './covers/Star Ocean: The Second Story R.png' },
  { name: 'Star Wars: The Force Unleashed v1.0.3', image: './covers/Star Wars: The Force Unleashed v1.0.3.png' },
  { name: 'Star Wars Jedi Knight: Jedi Academy v1.0.5', image: './covers/Star Wars Jedi Knight: Jedi Academy v1.0.5.png' },
  { name: 'Star Wars Jedi Knight II: Jedi Outcast v1.0.5', image: './covers/Star Wars Jedi Knight II: Jedi Outcast v1.0.5.png' },
  { name: 'Star Wars: Knights of the Old Republic', image: './covers/Star Wars: Knights of the Old Republic.png' },
  { name: 'Star Wars: Knights of the Old Republic II – The Sith Lords', image: './covers/Star Wars: Knights of the Old Republic II – The Sith Lords.png' },
  { name: 'Star Wars Episode I: Racer v1.0.4', image: './covers/Star Wars Episode I: Racer v1.0.4.png' },
  { name: 'Star Wars: Republic Commando v1.0.4', image: './covers/Star Wars: Republic Commando v1.0.4.png' },
  { name: 'Stardew Valley v1.5.4.2', image: './covers/Stardew Valley v1.5.4.2.png' },
  { name: 'Steins;Gate Elite', image: './covers/Steins;Gate Elite.png' },
  { name: 'Steven Universe: Save the Light', image: './covers/Steven Universe: Save the Light.png' },
  { name: 'OK K.O.! Let\'s Play Heroes', image: './covers/OK K.O.! Let\'s Play Heroes.png' },
  { name: 'Story of Seasons: Friends of Mineral Town', image: './covers/Story of Seasons: Friends of Mineral Town.png' },
  { name: 'Story of Seasons: Pioneers of Olive Town', image: './covers/Story of Seasons: Pioneers of Olive Town.png' },
  { name: 'Street Fighter 30th Anniversary Collection', image: './covers/Street Fighter 30th Anniversary Collection.png' },
  { name: 'Streets of Rage 4 + DLC (Bare Knuckle IV)', image: './covers/Streets of Rage 4 + DLC (Bare Knuckle IV).png' },
  { name: 'Subnautica', image: './covers/Subnautica.png' },
  { name: 'Subnautica: Below Zero', image: './covers/Subnautica: Below Zero.png' },
  { name: 'Sumikko Gurashi: Sumikko Park he Youkoso', image: './covers/Sumikko Gurashi: Sumikko Park he Youkoso.png' },
  { name: 'Super Bomberman R v1.4.2', image: './covers/Super Bomberman R v1.4.2.png' },
  { name: 'Super Mario 3D All-Stars 1.0.1', image: './covers/Super Mario 3D All-Stars 1.0.1.png' },
  { name: 'Super Mario 3D World + Bowser\'s Fury v1.1.0', image: './covers/Super Mario 3D World + Bowser\'s Fury v1.1.0.png' },
  { name: 'Super Mario Bros. Wonder 1.0.1', image: './covers/Super Mario Bros. Wonder 1.0.1.png' },
  { name: 'Super Mario Maker 2 v3.0.2', image: './covers/Super Mario Maker 2 v3.0.2.png' },
  { name: 'Super Mario Odyssey v1.3.0', image: './covers/Super Mario Odyssey v1.3.0.png' },
  { name: 'Super Mario Party v1.1.0', image: './covers/Super Mario Party v1.1.0.png' },
  { name: 'Super Mario Party Jamboree', image: './covers/Super Mario Party Jamboree.png' },
  { name: 'Super Mario RPG: Legend of the Seven Stars', image: './covers/Super Mario RPG: Legend of the Seven Stars.png' },
  { name: 'Super Robot Wars 30', image: './covers/Super Robot Wars 30.png' },
  { name: 'Super Robot Wars T', image: './covers/Super Robot Wars T.png' },
  { name: 'Super Robot Wars V', image: './covers/Super Robot Wars V.png' },
  { name: 'Super Smash Bros. Ultimate v2.0.1', image: './covers/Super Smash Bros. Ultimate v2.0.1.png' },
  { name: 'Super Street: Racer', image: './covers/Super Street: Racer.png' },
  { name: 'Super Zangyura v1.0.6', image: './covers/Super Zangyura v1.0.6.png' },
  { name: 'Surviving the Aftermath v1.20.1', image: './covers/Surviving the Aftermath v1.20.1.png' },
  { name: 'Sushi Striker: The Way of Sushido', image: './covers/Sushi Striker: The Way of Sushido.png' },
  { name: 'Sword Art Online: Alicization Lycoris', image: './covers/Sword Art Online: Alicization Lycoris.png' },
  { name: 'Sword Art Online: Fatal Bullet Complete Edition', image: './covers/Sword Art Online: Fatal Bullet Complete Edition.png' },
  { name: 'Sword Art Online: Hollow Realization Deluxe Edition', image: './covers/Sword Art Online: Hollow Realization Deluxe Edition.png' },
  { name: 'Tactics Ogre: Reborn v1.0.1', image: './covers/Tactics Ogre: Reborn v1.0.1.png' },
  { name: 'Taiko no Tatsujin: Drum \'n\' Fun!', image: './covers/Taiko no Tatsujin: Drum \'n\' Fun!.png' },
  { name: 'Taiko no Tatsujin: Rhythmic Adventure Pack', image: './covers/Taiko no Tatsujin: Rhythmic Adventure Pack.png' },
  { name: 'Taiko no Tatsujin: Rhythm Festival', image: './covers/Taiko no Tatsujin: Rhythm Festival.png' },
  { name: 'Taiko Risshiden V DX', image: './covers/Taiko Risshiden V DX.png' },
  { name: 'Tales of Vesperia: Definitive Edition', image: './covers/Tales of Vesperia: Definitive Edition.png' },
  { name: 'Taxi Chaos', image: './covers/Taxi Chaos.png' },
  { name: 'Teenage Mutant Ninja Turtles: Shredder\'s Revenge + DLC v1.0.7', image: './covers/Teenage Mutant Ninja Turtles: Shredder\'s Revenge + DLC v1.0.7.png' },
  { name: 'Teenage Mutant Ninja Turtles: The Cowabunga Collection', image: './covers/Teenage Mutant Ninja Turtles: The Cowabunga Collection.png' },
  { name: 'Temtem', image: './covers/Temtem.png' },
  { name: 'Terraria v1.0.3', image: './covers/Terraria v1.0.3.png' },
  { name: 'The Banner Saga Trilogy', image: './covers/The Banner Saga Trilogy.png' },
  { name: 'The Battle Cats Unite! + 3 DLC', image: './covers/The Battle Cats Unite! + 3 DLC.png' },
  { name: 'The Binding of Isaac: Repentance', image: './covers/The Binding of Isaac: Repentance.png' },
  { name: 'The Caligula Effect 2', image: './covers/The Caligula Effect 2.png' },
  { name: 'The Company Man', image: './covers/The Company Man.png' },
  { name: 'The DioField Chronicle', image: './covers/The DioField Chronicle.png' },
  { name: 'The Elder Scrolls V: Skyrim', image: './covers/The Elder Scrolls V: Skyrim.png' },
  { name: 'The House of the Dead: Remake v1.0.1', image: './covers/The House of the Dead: Remake v1.0.1.png' },
  { name: 'The King of Fighters XIII Global Match', image: './covers/The King of Fighters XIII Global Match.png' },
  { name: 'The Knight Witch v1.0.5', image: './covers/The Knight Witch v1.0.5.png' },
  { name: 'The Legend of Heroes: Ao no Kiseki: Kai', image: './covers/The Legend of Heroes: Ao no Kiseki: Kai.png' },
  { name: 'The Legend of Heroes: Hajimari no Kiseki', image: './covers/The Legend of Heroes: Hajimari no Kiseki.png' },
  { name: 'The Legend of Heroes: Sen no Kiseki I: Kai', image: './covers/The Legend of Heroes: Sen no Kiseki I: Kai.png' },
  { name: 'The Legend of Heroes: Sen no Kiseki II: Kai', image: './covers/The Legend of Heroes: Sen no Kiseki II: Kai.png' },
  { name: 'The Legend of Heroes: Sen no Kiseki III', image: './covers/The Legend of Heroes: Sen no Kiseki III.png' },
  { name: 'The Legend of Zelda: Breath of the Wild + 2 DLC v1.6.0', image: './covers/The Legend of Zelda: Breath of the Wild + 2 DLC v1.6.0.png' },
  { name: 'The Legend of Zelda: Echoes of Wisdom', image: './covers/The Legend of Zelda: Echoes of Wisdom.png' },
  { name: 'The Legend of Zelda: Link\'s Awakening', image: './covers/The Legend of Zelda: Link\'s Awakening.png' },
  { name: 'The Legend of Zelda: Skyward Sword HD', image: './covers/The Legend of Zelda: Skyward Sword HD.png' },
  { name: 'The Legend of Zelda: Tears of the Kingdom', image: './covers/The Legend of Zelda: Tears of the Kingdom.png' },
  { name: 'The Messenger v2.0.0', image: './covers/The Messenger v2.0.0.png' },
  { name: 'The Pathless', image: './covers/The Pathless.png' },
  { name: 'The Survivalists', image: './covers/The Survivalists.png' },
  { name: 'The Walking Dead: The Final Season v1.0.2', image: './covers/The Walking Dead: The Final Season v1.0.2.png' },
  { name: 'The Witcher 3: Wild Hunt – Complete Edition', image: './covers/The Witcher 3: Wild Hunt – Complete Edition.png' },
  { name: 'The Wonderful 101: Remastered', image: './covers/The Wonderful 101: Remastered.png' },
  { name: 'Theatrhythm Final Bar Line v1.0.1', image: './covers/Theatrhythm Final Bar Line v1.0.1.png' },
  { name: 'Titan Quest', image: './covers/Titan Quest.png' },
  { name: 'Toki Retrollector Edition', image: './covers/Toki Retrollector Edition.png' },
  { name: 'Tokyo Mirage Sessions #FE Encore', image: './covers/Tokyo Mirage Sessions #FE Encore.png' },
  { name: 'Touhou Mystia\'s Izakaya', image: './covers/Touhou Mystia\'s Izakaya.png' },
  { name: 'Transformers: Battlegrounds', image: './covers/Transformers: Battlegrounds.png' },
  { name: 'Trials of Mana (Seiken Densetsu 3)', image: './covers/Trials of Mana (Seiken Densetsu 3).png' },
  { name: 'Triangle Strategy v1.0.1', image: './covers/Triangle Strategy v1.0.1.png' },
  { name: 'Trine 5: A Clockwork Conspiracy v1.0.1', image: './covers/Trine 5: A Clockwork Conspiracy v1.0.1.png' },
  { name: 'Trinity Trigger', image: './covers/Trinity Trigger.png' },
  { name: 'TT Isle of Man', image: './covers/TT Isle of Man.png' },
  { name: 'TT Isle of Man Ride on the Edge 2', image: './covers/TT Isle of Man Ride on the Edge 2.png' },
  { name: 'Tunic v1.0.3', image: './covers/Tunic v1.0.3.png' },
  { name: 'Two Point Campus', image: './covers/Two Point Campus.png' },
  { name: 'Two Point Hospital + 4 DLC v1.0.6', image: './covers/Two Point Hospital + 4 DLC v1.0.6.png' },
  { name: 'Ultimate Chicken Horse v1.8.20', image: './covers/Ultimate Chicken Horse v1.8.20.png' },
  { name: 'Ultra Kaiju Monster Rancher', image: './covers/Ultra Kaiju Monster Rancher.png' },
  { name: 'Ultra Street Fighter II: The Final Challengers', image: './covers/Ultra Street Fighter II: The Final Challengers.png' },
  { name: 'Unbox: Newbie\'s Adventure', image: './covers/Unbox: Newbie\'s Adventure.png' },
  { name: 'Uncharted Waters IV with Power-Up Kit HD Version', image: './covers/Uncharted Waters IV with Power-Up Kit HD Version.png' },
  { name: 'Under Night In-Birth II Sys:Celes', image: './covers/Under Night In-Birth II Sys:Celes.png' },
  { name: 'Undertale', image: './covers/Undertale.png' },
  { name: 'Unicorn Overlord', image: './covers/Unicorn Overlord.png' },
  { name: 'Unravel Two', image: './covers/Unravel Two.png' },
  { name: 'Untitled Goose Game v1.1.0', image: './covers/Untitled Goose Game v1.1.0.png' },
  { name: 'Victor Vran Overkill Edition', image: './covers/Victor Vran Overkill Edition.png' },
  { name: 'Virche Evermore -ErroR:salvation-', image: './covers/Virche Evermore -ErroR:salvation-.png' },
  { name: 'Wand of Fortune R', image: './covers/Wand of Fortune R.png' },
  { name: 'WarioWare: Get It Together!', image: './covers/WarioWare: Get It Together!.png' },
  { name: 'WarioWare: Move It!', image: './covers/WarioWare: Move It!.png' },
  { name: 'Warriors Orochi 4 Ultimate + DLC', image: './covers/Warriors Orochi 4 Ultimate + DLC.png' },
  { name: 'Who Wants to Be a Millionaire?', image: './covers/Who Wants to Be a Millionaire?.png' },
  { name: 'Wild Card Football v1.0.1.0', image: './covers/Wild Card Football v1.0.1.0.png' },
  { name: 'Windstorm: An Unexpected Arrival', image: './covers/Windstorm: An Unexpected Arrival.png' },
  { name: 'Witch on the Holy Night', image: './covers/Witch on the Holy Night.png' },
  { name: 'Wolfenstein II: The New Colossus', image: './covers/Wolfenstein II: The New Colossus.png' },
  { name: 'Wonder Boy: The Dragon\'s Trap', image: './covers/Wonder Boy: The Dragon\'s Trap.png' },
  { name: 'WRC 8 FIA World Rally Championship', image: './covers/WRC 8 FIA World Rally Championship.png' },
  { name: 'WRC 9 FIA World Rally Championship', image: './covers/WRC 9 FIA World Rally Championship.png' },
  { name: 'WRC 10 FIA World Rally Championship', image: './covers/WRC 10 FIA World Rally Championship.png' },
  { name: 'WWE 2K18', image: './covers/WWE 2K18.png' },
  { name: 'Xenoblade Chronicles: Definitive Edition', image: './covers/Xenoblade Chronicles: Definitive Edition.png' },
  { name: 'Xenoblade Chronicles 2', image: './covers/Xenoblade Chronicles 2.png' },
  { name: 'Xenoblade Chronicles 2: Torna – The Golden Country', image: './covers/Xenoblade Chronicles 2: Torna – The Golden Country.png' },
  { name: 'Xenoblade Chronicles 3', image: './covers/Xenoblade Chronicles 3.png' },
  { name: 'Xuan Yuan Sword 7', image: './covers/Xuan Yuan Sword 7.png' },
  { name: 'Yomawari: The Long Night Collection', image: './covers/Yomawari: The Long Night Collection.png' },
  { name: 'Yo-Kai Watch 4++ + DLC', image: './covers/Yo-Kai Watch 4++ + DLC.png' },
  { name: 'Yooka-Laylee and the Impossible Lair', image: './covers/Yooka-Laylee and the Impossible Lair.png' },
  { name: 'Yoshi\'s Crafted World', image: './covers/Yoshi\'s Crafted World.png' },
  { name: 'Ys VIII: Lacrimosa of Dana', image: './covers/Ys VIII: Lacrimosa of Dana.png' },
  { name: 'Ys IX: Monstrum Nox', image: './covers/Ys IX: Monstrum Nox.png' },
  { name: 'Ys X: Nordics', image: './covers/Ys X: Nordics.png' },
  { name: 'Yuoni v1.0.4.2', image: './covers/Yuoni v1.0.4.2.png' },
  { name: 'Zombie Army 4: Dead War', image: './covers/Zombie Army 4: Dead War.png' },
  { name: 'Zumba Burn it Up!', image: './covers/Zumba Burn it Up!.png' }
];
